### ISSUE TITLE
实现打卡功能

### ISSUE THREAD

**Issue by cuixiaorui** [cuixueshe/earthworm#1]
类似于 github 

<img width="789" alt="image" src="https://github.com/cuixueshe/earthworm/assets/12064746/cc34af38-e131-4050-981d-6c2253ab6fe4">

完成一课后就可以记录下来

**Comment by lyuhailong** [comment]
打卡，第2课。

**Comment by baboon-king** [comment]
Github 的绿点统计有好几个纬度。commit pr issue 。。。
Earthworm 也可以 做成多个纬度的。比如每日打卡，完课，。。。
