### ISSUE TITLE
点击重新开始按钮提供二次确认的弹框

### ISSUE THREAD

**Issue by fengstats** [cuixueshe/earthworm#102]
## 原因

部分用户会使用 Tab，当多次 Tab 后会聚焦至重新开始按钮上，此时按下回车可能会导致进度被重置，例如：#55

当然也有用户不太确定按钮功能想点一下的情况，结果发现自己刚刚的进度就被清空了，对于用户体验并不友好~

## 期望

希望有在点击重新开始按钮时，有一个 Modal 弹框来询问用户 “是否确认清空进度？” 以保证避免误触的情况出现

**Comment by Zuowendong** [comment]
举手

**Comment by cuixiaorui** [comment]
good job！

这个二级弹框还可以在优化下用户体验

1. 点击空白区域可以直接关掉 - 方便鼠标用户 （不然还得移动到按钮处）
2. 取消和确定添加快捷键 - 方便键盘用户 （统一所有弹窗的快捷键触发）

**Comment by cuixiaorui** [comment]
done #119
