### ISSUE TITLE
添加星荣视频课程的入口

### ISSUE THREAD

**Issue by cuixiaorui** [cuixueshe/earthworm#115]
## what

添加星荣视频课程的入口

可以在这个位置加一个 video 的 icon ，点击后跳转到星荣 b站的视频

<img width="1271" alt="image" src="https://github.com/cuixueshe/earthworm/assets/12064746/33fdb9ca-31bd-4385-be88-0eee55d5353b">

## why

刷课的时候 大家有看视频的需求

这样可以让大家更方便一些

**Comment by vampirewy** [comment]
每节课对应还是直接一个链接

**Comment by lttztt** [comment]
统一跳到B站的第一节课就好吧。
