### ISSUE TITLE
MessageBox refactor

### ISSUE THREAD

**Issue by Nauxscript** [cuixueshe/earthworm#120]
重构 `client/components/main/MessageBox.vue`

预期：

- 外层可以使用 `v-model` 直接绑定 `show` 参数

内部可以用 `computed` 实现。

**Comment by Zuowendong** [comment]
> 内部可以用 computed 实现
没有使用computed实现
抽离封装成hooks，将props，emits和dom ref 作为参数传入，这导致了想写单测时候，这个抽离的useMessageBox()方法不知道怎么传入参数，期待一个单测学习学习
亦或是hooks封装的有点问题？

**Comment by Zuowendong** [comment]
pr #129 实现上感觉更好，学到了√
![微信截图_20240205101733](https://github.com/cuixueshe/earthworm/assets/45628596/5c49a04a-e1f5-42bd-a5d7-89b1d2cabd40)
