### ISSUE TITLE
移动端访问提示

### ISSUE THREAD

**Issue by cuixiaorui** [cuixueshe/earthworm#126]
## what

移动端进入 earthworm 的时候给予提示

告知用户现在只支持 pc 端 

## why

很多同学都是通过移动端进来的， 但是进来后 咱目前在移动端的样式全部是错乱的

所以给予一个提示在 pc 端访问 是非常有必要的

## how

可以是一个弹窗的形式 来通知

**Comment by WenYuan77** [comment]
我来我来

**Comment by liudewa888** [comment]
给个参考
![image](https://github.com/cuixueshe/earthworm/assets/62191686/7e3fdf93-cb46-485f-aeb2-9b40ade2a40a)

**Comment by cuixiaorui** [comment]
done #144
