### ISSUE TITLE
修改密码功能

### ISSUE THREAD

**Issue by Nauxscript** [cuixueshe/earthworm#141]

**Comment by SinglePoi** [comment]
再加个找回密码怎么样

**Comment by Nauxscript** [comment]
> 再加个找回密码怎么样

一般都是直接修改密码的吧 没有找回密码的；
不过要做修改密码功能就要绑定邮箱之类的

**Comment by cuixiaorui** [comment]
#142 如果有了第三方帐号登录的话 这个功能还需要吗？

**Comment by Nauxscript** [comment]
> #142 如果有了第三方帐号登录的话 这个功能还需要吗？

但是如果帐号密码登录的方式只要还保留，就得有修改密码的方式，可能有些人不愿意使用第三方登录的

**Comment by cuixiaorui** [comment]
done
