### ISSUE TITLE
输入内容是否应该限制为英文

### ISSUE THREAD

**Issue by SinglePoi** [cuixueshe/earthworm#143]
如图
![ex](https://github.com/cuixueshe/earthworm/assets/33282271/da2a8e05-cf1f-447a-a8c2-6547024560c3)

**Comment by Zuowendong** [comment]
我感觉应该没必要限制，以结果为导向，给用户一定的自由度，输入错了会有直接结果反馈，反正也不会通过，影响不大

**Comment by Nauxscript** [comment]
其实没有太大关系，因为用户也知道那里是输入英文的，而且输入中文必然是过不了验证的，这个不影响
