### ISSUE TITLE
对结果的实时反馈

### ISSUE THREAD

**Issue by ImSingee** [cuixueshe/earthworm#150]
如果输入了错误的单词直接变成红色（而不是最终敲下回车后才能感知是否正确）

我已经实现了相关效果，但是不太确定是否符合 earthworm 的设计意图，如果觉得有用我可以提交 PR 来实现

![CleanShot 2024-02-10 at 17 59 48](https://github.com/cuixueshe/earthworm/assets/11208082/9ac34a47-78c6-4802-838c-7c4a02be8d0d)

**Comment by cuixiaorui** [comment]
对于这个功能点的讨论可以看 #80 

错误应该是在最后提示给用户
这样不会打断用户的输入

核心是小步走/拆分

把输入句子和解决错误这两件事分离开

一开始输入的时候只关心句子
在回车后在关注解决错误

**Comment by cuixiaorui** [comment]
done
