### ISSUE TITLE
请问能不能在输入最后一个单词那里使用空格提交

### ISSUE THREAD

**Issue by NeilYeTAT** [cuixueshe/earthworm#154]
在输入英语单词的时候， 原本是写完句子后按回车键确认提交答案， 但是这样小拇指真的很难受啊🥹
能不能多添加个设置， 在输入到最后一个空的时候， 使用键入空格 === 提交
就类似中文输入法这样， 输入拼音后直接输入空格直接就选择了第一个选项

**Comment by Zuowendong** [comment]
希望你克服一下 (: 手动狗头

**Comment by cuixiaorui** [comment]
<img width="1324" alt="image" src="https://github.com/cuixueshe/earthworm/assets/12064746/fa3b907d-f9b1-4278-994d-7a641dfe5f80">
done
