### ISSUE TITLE
建议集成到 vscode 或 utools, 更方便学习摸鱼

### ISSUE THREAD

**Issue by yyyyy210** [cuixueshe/earthworm#160]
建议集成到 vscode 或 utools, 更方便学习摸鱼

**Comment by Nauxscript** [comment]
已有相关打算，估计等版本稳定了，会做这方面的落实

**Comment by cuixiaorui** [comment]
vscode 可以弄个套壳的插件
内部直接是 iframe 访问  earthworm.cuixueshe.com 
这部分功能可以另外起一个项目做
