### ISSUE TITLE
课程列表中当前课程高亮提示

### ISSUE THREAD

**Issue by zuowendong** [cuixueshe/earthworm#170]
## UI优化
当前课程进度学习中，点击进入课程列表，没有直接的返回课程进度的按钮
当前返回的操作有两种实现：
1. 点击正在学习的课程序列（用户可能忘记当前处于哪节课）
2. 点击左上角earthworm图标回到home页，再Get start进入

交互上用户体验不佳

## 期望
1. 高亮显示当前正在学习的课程序列框
2. 不同状态显示课程学习进度
3. 显示各课程完成次数情况

**Comment by cuixiaorui** [comment]
是的
可以来个 pr
