### ISSUE TITLE
无法成功注册

### ISSUE THREAD

**Issue by linzinl** [cuixueshe/earthworm#177]
注册填写 Name 时，不管输入什么，都会报400，返回报错 User already exists

**Comment by zhuzhux** [comment]
phone number 唯一，提示用户已存在

**Comment by cuixiaorui** [comment]
手机号已经被注册了
可以私聊我 重置帐号

**Comment by linzinl** [comment]
> 手机号已经被注册了 可以私聊我 重置帐号

我用另外一个手机号注册了，感谢
