### ISSUE TITLE
fix模式下,有多个单词输入错误,连续空格进入第二个错误单词,不能回退到第一个单词

### ISSUE THREAD

**Issue by liudewa888** [cuixueshe/earthworm#182]

**Comment by liudewa888** [comment]
![image](https://github.com/cuixueshe/earthworm/assets/62191686/bf7d0c1e-4323-41d0-9879-bfdb857b9c6b)

**Comment by cuixiaorui** [comment]
done 
现在支持通过 backspace 回到上一个错误的单词上
