### ISSUE TITLE
今天排行榜数据丢失了

### ISSUE THREAD

**Issue by rockyhu** [cuixueshe/earthworm#187]
今天排行榜数据丢失了，rockyhu，已经学习到第十课了。

**Comment by rockyhu** [comment]
<img width="1346" alt="image" src="https://github.com/cuixueshe/earthworm/assets/15012307/bcd6da7e-e40d-4645-9a53-b9546026d1f8">

**Comment by rockyhu** [comment]
<img width="1271" alt="image" src="https://github.com/cuixueshe/earthworm/assets/15012307/4bdeb9bd-9b53-410a-b7d8-41bb2c381977">

**Comment by fengstats** [comment]
感谢反馈，不过排行榜是会定期重置的嗷，可以参考这个 issue https://github.com/cuixueshe/earthworm/issues/134

**Comment by Nauxscript** [comment]
一天刷了10课吗😂

**Comment by fengstats** [comment]
这也是我们处于对新用户的考虑，课程排行榜一直累积的话，由老用户霸榜之后，新用户将很难上榜，可能会导致新用户刷课的动力丢失，还望理解，冲冲冲，继续霸榜！😊

**Comment by rockyhu** [comment]
> 一天刷了10课吗😂

有一到两个周了。周五晚上搞完第九课，今天再次进来的时候排行榜数据就清空了。

**Comment by rockyhu** [comment]
> 这也是我们处于对新用户的考虑，课程排行榜一直累积的话，由老用户霸榜之后，新用户将很难上榜，可能会导致新用户刷课的动力丢失，还望理解，冲冲冲，继续霸榜！😊

感觉也还挺影响老用户的动力的。

**Comment by fengstats** [comment]
> > 一天刷了10课吗😂
> 
> 有一到两个周了。周五晚上搞完第九课，今天再次进来的时候排行榜数据就清空了。

目前应该是开启了每周一重置的定时任务

**Comment by rockyhu** [comment]
> > > 一天刷了10课吗😂
> > 
> > 
> > 有一到两个周了。周五晚上搞完第九课，今天再次进来的时候排行榜数据就清空了。
> 
> 目前应该是开启了每周一重置的定时任务

收到，虽然有影响，但还是尊重大佬的决定，重新开始。

**Comment by fengstats** [comment]
> > > > 一天刷了10课吗😂
> > > 
> > > 
> > > 有一到两个周了。周五晚上搞完第九课，今天再次进来的时候排行榜数据就清空了。
> > 
> > 
> > 目前应该是开启了每周一重置的定时任务
> 
> 收到，虽然有影响，但还是尊重大佬的决定，重新开始。

是的，我也理解突然刷了这么多课一下排名被清空了，是有点难受，这个我很抱歉~ 

但怎么说呢，就我而言重置的方案是要更优一点的，因为每周重置后大家都回归同一起跑线了，一周内你想排名靠前，那就多得刷，就会有更多的用户参与进来，游戏就是要大家一起玩才有意思 😊

排行榜重置功能也是根据群内多数用户反馈而上线的，对了，你是不是没有加群啊，可以添加下崔哥的 wx 让他拉你进群：cuixr1314

**Comment by fengstats** [comment]
> > > > 一天刷了10课吗😂
> > > 
> > > 
> > > 有一到两个周了。周五晚上搞完第九课，今天再次进来的时候排行榜数据就清空了。
> > 
> > 
> > 目前应该是开启了每周一重置的定时任务
> 
> 收到，虽然有影响，但还是尊重大佬的决定，重新开始。

芜湖！感谢理解 🙏

**Comment by Nauxscript** [comment]
> > > > 一天刷了10课吗😂
> > > 
> > > 
> > > 有一到两个周了。周五晚上搞完第九课，今天再次进来的时候排行榜数据就清空了。
> > 
> > 
> > 目前应该是开启了每周一重置的定时任务
> 
> 收到，虽然有影响，但还是尊重大佬的决定，重新开始。

后续排行榜的记录和实际的记录会分开，排行榜显示的是当周的刷课次数；在个人资料会记录你所有的刷题记录；
