### ISSUE TITLE
实现分享图显示通关时长

### ISSUE THREAD

**Issue by cuixiaorui** [cuixueshe/earthworm#200]
<img width="750" alt="image" src="https://github.com/cuixueshe/earthworm/assets/12064746/1e5eb85b-9c30-4539-9388-5393d4af173b">

## 实现思路

在开始答题的时候记录一个开始时间戳
在弹出结束面板的时候基于当前的时间戳 - 开始时间戳  = 总用时

## why

让大家有个竞争感和炫耀感

“你看我用时那么短 厉害吧”

“我不服 你等着  看我比你用时还要短” [旺柴]

**Comment by zuowendong** [comment]
如果刷题中途，浏览器“意外”关闭，时间怎么计算？

**Comment by fengstats** [comment]
> 如果刷题中途，浏览器“意外”关闭，时间怎么计算？

感觉是不是可以在刷题页面设计一个类似 qwerty 的工具栏显示，如

![1709804008259](https://github.com/cuixueshe/earthworm/assets/48991003/12ec1f65-baca-4805-a7c3-0bb1923a828a)

不过确实浏览器意外关闭或用户主动关闭的情况（比如切换课程）也需要考虑一下措施规避异常，我感觉是不是可以不要等结束才计算，而是使用一个定时器来记录用户正常输入的时间，如果用户长时间（30s）还没有任何输入，则暂停输入计时，主动关闭或者异常关闭自然也不会被记录时间

至于有没有更好的方案，以及用户主动切换课程时又该如何处理，我认为可以讨论一下
