### ISSUE TITLE
[重构] - 重新设计用户信息页面的相关样式

### ISSUE THREAD

**Issue by cuixiaorui** [cuixueshe/earthworm#216]
<img width="1227" alt="image" src="https://github.com/cuixueshe/earthworm/assets/12064746/39021b9a-c337-49d7-bf5c-7106737dc666">

<img width="1220" alt="image" src="https://github.com/cuixueshe/earthworm/assets/12064746/ff9b7924-f321-485e-9277-30c7ec36d960">

之前是临时写的样式 

现在需要重新设计 弄的更漂亮点

可以先出一版设计

大家讨论没问题后 再开始动手

**Comment by Nauxscript** [comment]
我晚点做个设计图看看

**Comment by zuowendong** [comment]
设计上可能还需要考虑可扩展的模块该怎么放置布局，例如 issue #125

**Comment by yaolifeng0629** [comment]
- V0.1
  - 要不我们实现一个 v0.1 版本的，后续可在迭代，现在有点太简洁了。参考了下（Relingo）
![image](https://github.com/cuixueshe/earthworm/assets/88535417/7c1d12f9-9c41-484d-a07c-8eb1e97fdef9)
