### ISSUE TITLE
为啥不加个previous呢？

### ISSUE THREAD

**Issue by 1Telescope1** [cuixueshe/earthworm#218]
![4238126783](https://github.com/cuixueshe/earthworm/assets/108674631/72e31cdb-cb8e-4c36-bdb6-1d41fceaa19c)

**Comment by zuowendong** [comment]
已经存在again了呀
那向前一步回退的操作的意义是什么呢？
如果想回顾的话，完全可以再刷一遍，我们也鼓励多重复

**Comment by fengstats** [comment]
目前功能已经实现，具体查看 #434 😊
