### ISSUE TITLE
注册功能提示“Bad Request Exception”，导致无法注册。

### ISSUE THREAD

**Issue by jokecode** [cuixueshe/earthworm#219]
#### 在官网注册时提示“Bad Request Exception”，导致无法注册。
![image](https://github.com/cuixueshe/earthworm/assets/18712110/2dfb7725-9a13-404e-90f3-62af27a80445)

#### 将该项目克隆到本地后，进行注册报同样的错误。
![image](https://github.com/cuixueshe/earthworm/assets/18712110/7dae9bdd-b600-4865-8a08-f29cfd0edc49)

**Comment by fengstats** [comment]
不好意思，密码目前后端是限制长度在 6-20 位的，但前端注册时只提示了 6 位以上即可，后续会更新验证以及提示文案~

**Comment by jokecode** [comment]
> 不好意思，密码目前后端是限制长度在 6-20 位的，但前端注册时只提示了 6 位以上即可，后续会更新验证以及提示文案～

确实是密码太长了，我换了一个短密码就可以成功注册了。
