### ISSUE TITLE
区分大小写、扩充答案的多样性

### ISSUE THREAD

**Issue by caaaaaleb** [cuixueshe/earthworm#227]
1.区分大小写，比如每个句子首个单词的首字母、一些特定的词比如“I”（我）需要大写；
![Snipaste_2024-03-11_20-54-25](https://github.com/cuixueshe/earthworm/assets/15030089/1b761410-11be-4eae-835d-37b4f08bfdd9)
2.扩充答案的多样性
（1）比如“吃”，我的第一反应是“eat”而不是“to eat”，而“to eat”也不是固定搭配，再这个系统里如果不写“to eat”就会返回错误，而：食物“前面也不一定要加”the“,这样可能显得有点教条；
（2）英文中同一个意思可能有很多种表达方式，比如”grub“也可以翻译成”食物“，如果输入”grub“发现错误的话有些人可能会觉得奇怪
![Snipaste_2024-03-11_20-48-05](https://github.com/cuixueshe/earthworm/assets/15030089/408c695c-b820-4824-833c-038f5700783d)
![Snipaste_2024-03-11_20-48-05](https://github.com/cuixueshe/earthworm/assets/15030089/cf0f7d9f-bdc7-4fc8-a27f-9406f76cba1a)

**Comment by cuixiaorui** [comment]
问题一：

现在就是支持

问题二：

这是因为 earthworm 以句子为核心导致的问题
最后需要拼成一个句子
但是确实是有用户看到中文输入n个单词后才正确的问题
不过对于这个问题 现在可以通过两种方案解决
1. 播放声音 通过声音知道要输入的单词是什么
2. 看答案 有时候播放声音不太确定的时候 就可以看下答案  回来在继续输入就好了
<img width="377" alt="image" src="https://github.com/cuixueshe/earthworm/assets/12064746/f8304d20-9117-4dff-960e-682557e98ccf">
