### ISSUE TITLE
Synology NAS 支持

### ISSUE THREAD

**Issue by chllei** [cuixueshe/earthworm#232]
大神您好，您的项目真的好赞。想知道一下，这个有办法友好地部署在群晖 NAS 上吗？这样就能实现家庭私有化部署、练习了。

**Comment by cuixiaorui** [comment]
不好意思 对于 群晖 NAS 不是太熟悉

咱这个项目可以通过 docker 部署

你可以看看 NAS 是否支持 docker 部署
