### ISSUE TITLE
[优化] - 增加常用词映射功能用于用户自定义缩写词汇

### ISSUE THREAD

**Issue by Andecheal** [cuixueshe/earthworm#238]
如：
通过dont --> 指代don't
![image](https://github.com/cuixueshe/earthworm/assets/47469230/ee75a746-adfa-4463-beed-d1b68499d9d4)

**Comment by lzdml** [comment]
最多也就是do not

**Comment by Andecheal** [comment]
不讨论表达是否符合英语标准，映射功能可以提高不同输入习惯用户的使用体验

另外: dont敲习惯了，感谢指正😅

**Comment by cuixiaorui** [comment]
后续会增加掌握列表  已经掌握的单词将不会在出现在练习中
