### ISSUE TITLE
编写 README

### ISSUE THREAD

**Issue by hildxd** [cuixueshe/earthworm#24]
- [x] 如何启动项目
- [x] 提供英文版文档

**Comment by Zuowendong** [comment]
希望能提供一个window版本的安装说明文档，pnpm install 卡在了安装 argons
![install fail](https://github.com/cuixueshe/earthworm/assets/45628596/4f699e02-394e-485d-8c2c-a7b1291ea1bc)

**Comment by hildxd** [comment]
> 希望能提供一个window版本的安装说明文档，pnpm install 卡在了安装 argons ![install fail](https://private-user-images.githubusercontent.com/45628596/300355890-4f699e02-394e-485d-8c2c-a7b1291ea1bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1NDEwMTMsIm5iZiI6MTcwNjU0MDcxMywicGF0aCI6Ii80NTYyODU5Ni8zMDAzNTU4OTAtNGY2OTllMDItMzk0ZS00ODVkLThjMmMtYTdiMTI5MWVhMWJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDE1MDUxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4NzI0ZGE0MWUwNWY1MmE3ZWI0ZGYyYjEyZTBhNjk3NDQ3YjkzMDY5N2M3N2Y5NDA3ZDM1NDAzY2ZiOTQ3MGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.j64q5h8wBA75MXEGOCm4TuASk-iJMViQAnslNv4KKVA)

已经喊朋友帮忙安排了，earthworm群里讨论过了这个问题

**Comment by fengstats** [comment]
> 希望能提供一个window版本的安装说明文档，pnpm install 卡在了安装 argons ![install fail](https://private-user-images.githubusercontent.com/45628596/300355890-4f699e02-394e-485d-8c2c-a7b1291ea1bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1NDQyMzgsIm5iZiI6MTcwNjU0MzkzOCwicGF0aCI6Ii80NTYyODU5Ni8zMDAzNTU4OTAtNGY2OTllMDItMzk0ZS00ODVkLThjMmMtYTdiMTI5MWVhMWJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDE1NTg1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwNWZmZGEwNTYyOGM2OTkyYWFlOWY3Yzk2MGNhYmJhN2E3NWE5YTRmMGI1YTYyYzg0ZTlkZjQ0NzQwMmJmYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WDa_hHXJLERtlRZt7TSxx-IjA6lhBkvmn3HP8mxNUxU)

可以看看这个 PR 是否解决了你的问题：https://github.com/cuixueshe/earthworm/pull/61

**Comment by fengstats** [comment]
目前 README 中英文文档的编写已经基本完成，后续有其他问题可以开一个新的 issues 讨论~ 🎉
