### ISSUE TITLE
【Bug】部分长句会出现 功能区域 与 中文含义 重叠！

### ISSUE THREAD

**Issue by yaolifeng0629** [cuixueshe/earthworm#249]
例如：第三十课
<img width="683" alt="Snipaste_2024-03-12_20-43-09" src="https://github.com/cuixueshe/earthworm/assets/88535417/ecc51bd1-a839-4628-b6dc-976cefce5f02">

**Comment by Nauxscript** [comment]
related to #210

**Comment by fengstats** [comment]
@yaolifeng0629 已修复，线上版本体验 😊
