### ISSUE TITLE
去掉 .5 的 title 的课程

### ISSUE THREAD

**Issue by cuixiaorui** [cuixueshe/earthworm#251]
### Description

<img width="1188" alt="image" src="https://github.com/cuixueshe/earthworm/assets/12064746/2c4c246f-d8ce-43f2-a439-15c9aa7e7b16">

这里的第 5.5 课 直接改成第 6 课  

原第 6 课的 title 变成第 7 课

后面课程的 titile 以此类推

不在和视频课程对齐， 课程内通过 小电视按钮跳转就好了

**Comment by Torstentjh** [comment]
I want to take it.
