### ISSUE TITLE
[功能] - 给课程列表中课程卡片添加练习点描述

### ISSUE THREAD

**Issue by cuixiaorui** [cuixueshe/earthworm#252]
### Description

<img width="1112" alt="image" src="https://github.com/cuixueshe/earthworm/assets/12064746/35c46ad7-3839-43dd-88f6-2c384610f330">
类似于这样

## why

用户就能知道对应的学习内容了

## how

课程的描述内容 可以在 courseLinks.json 里面进行扩展
<img width="997" alt="image" src="https://github.com/cuixueshe/earthworm/assets/12064746/59b1ca81-374e-4310-904d-1c3cffa142fe">

## 难点

- 你需要过一遍每节课的内容 然后才能知道填写什么描述（可以尝试借助 ai 完成）

**Comment by XmchxUp** [comment]
I want to take it.
