### ISSUE TITLE
[优化] - 游戏页进入课程列表时自动定位到当前课程卡片位置

### ISSUE THREAD

**Issue by cuixiaorui** [cuixueshe/earthworm#253]
### Description

进入 courses page 后需要定位到对应的 course card

进入 courses 页面
<img width="1205" alt="image" src="https://github.com/cuixueshe/earthworm/assets/12064746/1c3148b7-cbf5-43f3-ade1-fc40a211421a">

现在
<img width="1227" alt="image" src="https://github.com/cuixueshe/earthworm/assets/12064746/310a00ed-5846-4987-a344-2273e0de11e6">

期望
需要自动滚动到 active course card 的位置

<img width="1219" alt="image" src="https://github.com/cuixueshe/earthworm/assets/12064746/80500652-3f2c-444e-b546-0ca03e0065ef">

**Comment by fengstats** [comment]
目前还有点问题，在本地开发时可以正常滚动到当前 course card 位置，但是打包之后就不行了
