### ISSUE TITLE
Leaderboard pop-ups

### ISSUE THREAD

**Issue by Xiaozuoyi** [cuixueshe/earthworm#264]
### Description

[CleanShot 2024-03-14 at 10 57 20@2x](https://github.com/cuixueshe/earthworm/assets/94602408/eb4ea352-0ae9-4dc5-a589-b47ad1318e14)

希望增加点击弹出窗口外或 Esc 按钮退出弹出窗口的功能

**Comment by cuixiaorui** [comment]
done #393
