### ISSUE TITLE
[BUG] - Unable to enter text after resetting course progress

### ISSUE THREAD

**Issue by Xiaozuoyi** [cuixueshe/earthworm#265]
### Describe the bug

到达一定到课程进度，重置课程进度后。导致无法输入文本
复现步骤：

1. 完成单词到第二个单词，输入错误单词后，回车。
2. 然后点击重置，确认重置。
3. 回到第一个单词后，点击input框。

下面是错误消息：
![CleanShot 2024-03-14 at 12 00 17@2x](https://github.com/cuixueshe/earthworm/assets/94602408/62479eb8-f84f-45ee-90e2-6f8693e953c9)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/cuixueshe/earthworm/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/cuixueshe/earthworm/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by fengstats** [comment]
related to #194

**Comment by fengstats** [comment]
已修复，详情请见 https://github.com/cuixueshe/earthworm/pull/247
