### ISSUE TITLE
第六课程一处数据有误

### ISSUE THREAD

**Issue by sg996** [cuixueshe/earthworm#269]
### Describe the bug

第六课  id 为 80104 课程数据 中文有误
<img width="479" alt="微信图片_20240314204526" src="https://github.com/cuixueshe/earthworm/assets/46132798/f3e0f947-140d-414f-996b-ee9faadf596c">

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/cuixueshe/earthworm/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/cuixueshe/earthworm/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sg996** [comment]
<img width="427" alt="微信图片_20240314205441" src="https://github.com/cuixueshe/earthworm/assets/46132798/03f0bd79-cf66-43f7-b561-ae422b56aadf">
经过检查有两处错误

**Comment by sg996** [comment]
经检查数据，id为 80102、80104、80106项，chinese中的 它们 需要修改为 他们

<img width="1080" alt="微信图片_20240314210113" src="https://github.com/cuixueshe/earthworm/assets/46132798/2f57ec90-ddb7-466b-af46-8f56e5c6c495">

**Comment by fengstats** [comment]
hello，在英文中经常会出现一词多义，they 可以指代男性他们、女性她们、一群人或是物或事，所以并没有什么问题

在你所认为最后一处错误标记也可以体现，“你们需要尽快回答工作的问题因为 **它们** 是非常重要的” 这里肯定是用 “它们” 而不是 “他们”，所谓工作的问题并不是 “人” 而是 “事”

对了，我们的课程数据是来自于 B 站这个 UP 星荣，关于这部分你如果还有疑问，可以请教一下他，这里把具体学习语句的跳转时间链接附上：https://www.bilibili.com/video/BV13L4y1p7NW?t=2577.9

希望能解答你疑惑 😊

**Comment by sg996** [comment]
谢谢解答

**Comment by fengstats** [comment]
> 谢谢解答

芜湖！能帮到你就好~
