### ISSUE TITLE
[Feature Request] - 为啥 next 和 again 不加一个快捷键呢，在快捷键和鼠标之间切换非常不方便

### ISSUE THREAD

**Issue by SouthLink** [cuixueshe/earthworm#271]
### Clear and concise description of the problem

为啥 next 和 again 不加一个快捷键呢，在快捷键和鼠标之间切换非常不方便，而且 next 和 again 希望增加快捷键的设置

### Suggested solution

为啥 next 和 again 不加一个快捷键呢，在快捷键和鼠标之间切换非常不方便，而且 next 和 again 希望增加快捷键的设置

**Comment by z740332251** [comment]
用tab+回车就可以了

**Comment by fengstats** [comment]
hello~ 其实是有快捷键的，详情请见主页左下角小框中的

![1710479598749](https://github.com/cuixueshe/earthworm/assets/48991003/8484fcae-cc5d-4147-afeb-abc3b077069b)

**Comment by SouthLink** [comment]
> hello~ 其实是有快捷键的，详情请见主页左下角小框中的
> 
> ![1710479598749](https://private-user-images.githubusercontent.com/48991003/313075393-8484fcae-cc5d-4147-afeb-abc3b077069b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0ODIzMTIsIm5iZiI6MTcxMDQ4MjAxMiwicGF0aCI6Ii80ODk5MTAwMy8zMTMwNzUzOTMtODQ4NGZjYWUtY2M1ZC00MTQ3LWFmZWItYWJjM2IwNzcwNjliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE1VDA1NTMzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2N2Q1NTc1ZjhlMzQzYzNlY2ZhMTRiODc1YWE1MjMyZDQ4N2VmNWVjN2I4ZTM1M2U1NTQ0OGNlZWIxZGFiMWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.O-Nv2WLIDwviZVFSh6yFcfbImxzExGcouhcNZ8Bolwk)

谢谢，课程下面没看到，感觉不太明显
