### ISSUE TITLE
[BUG] - 官网练习单词不能播放声音

### ISSUE THREAD

**Issue by Xiaolong00** [cuixueshe/earthworm#272]
### Describe the bug

 官网练习单词不能播放声音，F12报错

### Reproduction

https://earthworm.cuixueshe.com/main/1

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/cuixueshe/earthworm/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/cuixueshe/earthworm/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by fengstats** [comment]
你好，我并不能复现你所说的场景，是否能补充详细一点的操作流程，比如

1. 点击底部提示区域按钮不能播放？
2. 使用快捷键不能播放？
3. 什么场景下？

还有一种情况可能是你的网络不佳，因为目前我们是直接调用网页有道的音频 API，如果网络不太好的话也播放不出来 😊

**Comment by cuixiaorui** [comment]
缺少复现步骤&报错信息
