### ISSUE TITLE
更改保存进度逻辑

### ISSUE THREAD

**Issue by hildxd** [cuixueshe/earthworm#28]
- [ ] 用户打开页面 找到 activeCourseId
- [ ] 然后服务端把 这个courseId 的数据的 statement 数据都给前端
- [ ] 查看 localstorage  有没有这个 courseId 的 statementIndex

**Comment by Nauxscript** [comment]
未登录状态：
- 在主页直接回车，如果 `localstorage.activedCourseId` 为空，则进入第一课，做完第一课后，`localstorage.activedCourseId` 为 `-1-2`（值结构是 `<userId>-<courseId>`），未登录 `userId` 为 -1，`2` 为 第二课的 `id`；
- 在主页直接回车，如果 `localstorage.activedCourseId`  为 `-1-2`（已经体验过第一课），弹窗 “需要登录”
- 做第二课，拦截，提示弹窗 “需要登录”；确认跳转注册页，取消回到主页

登录状态：
- 每完成一课后，更新 `localstorage.activedCourseId` 为 `<userId>-<下一课 id>`
- 进入主页时，通过接口获取当前的进度（`courseId`）,  在主页回车时，直接进入对应课程
