### ISSUE TITLE
实现切换英音/美音

### ISSUE THREAD

**Issue by cuixiaorui** [cuixueshe/earthworm#296]
### Description

可以在个人设置页面加上选择按钮

需要看看 有道api 是否支持

**Comment by HolinWang** [comment]
在个人设置页面加上选择按钮

![image](https://github.com/cuixueshe/earthworm/assets/99414027/438b70ad-14dc-460b-b3ed-e8bd0ff29ffb)

**Comment by fengstats** [comment]
已添加~
