### ISSUE TITLE
实现付费页面

### ISSUE THREAD

**Issue by cuixiaorui** [cuixueshe/earthworm#299]
### Description

<img width="1268" alt="image" src="https://github.com/cuixueshe/earthworm/assets/12064746/7eb8fdc5-7c41-44b1-8f30-9a69ca464f12">

类似这种

**Comment by yaolifeng0629** [comment]
receive~

**Comment by yaolifeng0629** [comment]
1. 刚简单实现了付费页面，如下图：
![34255155-0fa7-4adb-8632-8e4d26024adf](https://github.com/cuixueshe/earthworm/assets/88535417/81436967-06f5-41c1-8bca-c11158780211)

**Comment by ishowman** [comment]
部署本地使用的话需要付费吗

**Comment by yaolifeng0629** [comment]
已于 #342  合并！
