### ISSUE TITLE
[功能] - 支持多课程包

### ISSUE THREAD

**Issue by cuixiaorui** [cuixueshe/earthworm#300]
### Description

后续我们需要扩展多个课程包

星荣的只是其中的一个课程包
		- 后面会有n个
		- 多课程包的入口
			- ![image.png](https://images-1252602850.cos.ap-beijing.myqcloud.com/20240317110807.png)
		- 课程包里面包含多个课
			- ![image.png](https://images-1252602850.cos.ap-beijing.myqcloud.com/20240317110831.png)

**Comment by cuixiaorui** [comment]
## Tasking

- [ ] 创建 coursePack schema
- [ ] 修改 course schema  新增字段
- [ ] 实现课程包列表的接口
- [ ] 实现单个课程包详情的接口
- [ ] 实现课程的句子列表的接口
- [ ] 非免费课必须是会员才允许访问

**Comment by cuixiaorui** [comment]
done

**Comment by kkpapa** [comment]
抱歉，这个issue close掉了，但没看太明白。现在是支持了多课程包，但是不是还不支持自定义自己的课程包？没有看到增加自定义课程包的说明文档，谢谢。
