### ISSUE TITLE
[BUG] - 学习完第 9 课之后自动退出登录 & 且学习记录消失

### ISSUE THREAD

**Issue by hyhkjiy** [cuixueshe/earthworm#308]
**问题出现时间**：2024/03/18 9:50左右
**浏览器**：Chrome
**操作系统**：macOS Ventura 13.4
**问题过程描述**：
这是学习完成第9课的打卡截图：
![image](https://github.com/cuixueshe/earthworm/assets/18144117/6b478c28-63af-4c96-a1fc-8e578e5b3435)
当我点击开始下一课之后直接跳转到了登录页面，输入手机号和密码提示登录失败。然后跳转到主页又发现已经登录了，跳转到课程列表发现第9课的学习记录消失。
![image](https://github.com/cuixueshe/earthworm/assets/18144117/679d3a3e-1259-4fa4-95ce-41bfcd735f57)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/cuixueshe/earthworm/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/cuixueshe/earthworm/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by easylee1996** [comment]
有同样的问题，出现两次了，学习的时候没提示要登录，等到打卡时就提示登录，然后打开记录消失了

**Comment by hyhkjiy** [comment]
今天再次遇到这个问题，不同的是我学完13课被迫重新登录之后，后面并没有学习过的14～21课也被打上了学过一次的标记。
![image](https://github.com/cuixueshe/earthworm/assets/18144117/d9860e5d-cb84-4114-b207-07707a8a9323)

**Comment by fengstats** [comment]
@hyhkjiy 好的收到！问题正在追查~

**Comment by cuixiaorui** [comment]
重写了这部分的逻辑
大家可以在试试
