### ISSUE TITLE
长句子输入完毕后,其中一个单词反复输入错误,看完答案返回后,之前输入正确内容也被清空了

### ISSUE THREAD

**Issue by liudewa888** [cuixueshe/earthworm#315]
### Description

现状: 长句子输入完毕后,其中一个单词反复输入错误,看完答案返回后,之前输入正确内容也被清空了
![image](https://github.com/cuixueshe/earthworm/assets/62191686/791f8f18-830e-406b-8fa5-975ca197f884)
预期: 看完答案后,不进行清空,或者只看输入错误单词的答案

**Comment by cuixiaorui** [comment]
#386 
现在改变了看答案的方式  
可以解决你这问题了
