### ISSUE TITLE
[BUG] - 第十二课一处错误

### ISSUE THREAD

**Issue by sg996** [cuixueshe/earthworm#324]
### Describe the bug

对应课程时间：[1:01:15](https://www.bilibili.com/video/BV1pb4y1e7Uc/?vd_source=eef3950cfbf8a7ca900c6cd55a506775)
![image](https://github.com/cuixueshe/earthworm/assets/46132798/9c91bd42-9c64-4269-94e1-5e6871c4bd52)
<img width="608" alt="微信图片_20240319235201" src="https://github.com/cuixueshe/earthworm/assets/46132798/19cad1a1-345a-482a-949c-97bb26427319">

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/cuixueshe/earthworm/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/cuixueshe/earthworm/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sg996** [comment]
经体验，发现数据 id 为 2596、2642（[1:43:41](https://www.bilibili.com/video/BV1pb4y1e7Uc/?vd_source=eef3950cfbf8a7ca900c6cd55a506775)）、2644（[1:44:05](https://www.bilibili.com/video/BV1pb4y1e7Uc/?vd_source=eef3950cfbf8a7ca900c6cd55a506775)）、2650（[1:44:52](https://www.bilibili.com/video/BV1pb4y1e7Uc/?vd_source=eef3950cfbf8a7ca900c6cd55a506775)）、2658（[1:46:10](https://www.bilibili.com/video/BV1pb4y1e7Uc/?vd_source=eef3950cfbf8a7ca900c6cd55a506775)） 数据 don't 识别有误，填写单词时拆分成两个填空了

[数据内容](http://jsont.run/cRLVlzzXvL8TV72ddCYWs)

![image](https://github.com/cuixueshe/earthworm/assets/46132798/52ec10fd-f882-4116-ab67-2ff7b07c55dc)

**Comment by fengstats** [comment]
Looks good to me! 目前最新的数据存放位置在：packages/xingrong-courses/data/courses，欢迎 pr 😊
