### ISSUE TITLE
[BUG] - login 的时候报错： register error

### ISSUE THREAD

**Issue by zeekerpro** [cuixueshe/earthworm#329]
### Describe the bug

![WX20240320-084729](https://github.com/cuixueshe/earthworm/assets/29775830/afe8ccbb-5592-4992-81c0-e0dd375cd5df)
之前一直是登陆状态，今天早上练习了一课，网页退出登陆了，然后login就报错register error，一直无法login

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/cuixueshe/earthworm/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/cuixueshe/earthworm/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by cuixiaorui** [comment]
尝试重新注册一下

**Comment by xpfo-go** [comment]
> 尝试重新注册一下

same bug

**Comment by xpfo-go** [comment]
> 尝试重新注册一下

重新注册之后好了

**Comment by zeekerpro** [comment]
nice
