### ISSUE TITLE
使用 docker 部署遇到的问题

### ISSUE THREAD

**Issue by phken91** [cuixueshe/earthworm#336]
### Description

作者你好, 我在使用 docker 封装你的应用的时候, 在进行初始化的时候遇到了一些问题:
1. 进行 db:init, 会出现 `Err: No schema files found for path config ['../../libs/shared/src/schema/*']` 的问题
应该是路劲不能自动解析所导致
2. 另一个问题是关于 cors 的问题, 因为在cors 的设定, 你 hardcode 两个网域, `localhost` & `earthworm.cuixueshe.com`
这里的话, 能否从环境变数去读取 cors 的设定? 目前是直接透过修改源代码来越过这部分

封装脚本可以查阅: 
https://gist.github.com/phken91/cee8889919fe92cebeb4a3040602177b

感谢你

**Comment by fengstats** [comment]
你好，关于第一个问题已经解决，可以拉取最新代码测试下

**Comment by cuixiaorui** [comment]
CORS 可以在 api 项目里面设置允许 localhost
