### ISSUE TITLE
[BUG] - 12课的249 answer 这个单词有bug

### ISSUE THREAD

**Issue by Domainsun** [cuixueshe/earthworm#337]
### Describe the bug

![Uploading WechatIMG218.jpg…]()

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/cuixueshe/earthworm/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/cuixueshe/earthworm/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zclsx** [comment]
asnwer， 你指的是这个吗？ 在12课的课程内容中。 
目前关于asnwer在课程已经修复，下次更新就会同步
