### ISSUE TITLE
[功能] - 增加普通用户名和密码登录

### ISSUE THREAD

**Issue by cuixiaorui** [cuixueshe/earthworm#338]
## what

现在是基于手机号作为帐号的

不过我们其实用不到手机号 

等到后面有付费功能的时候在采用手机号的方式登录 （手机号需要走验证码）

让用户自己随便用个帐号来注册就好了

## how

之前表里面存的是 phone

换成普通的帐号需要注册格式的处理

需要思考兼容性上的问题

原有的手机号验证逻辑需要保留封装到组件中

（后续用的到）

**Comment by baboon-king** [comment]
从注册界面上：
1. 移除(隐藏)手机号的录入功能
2. 增加 username 录入
3. 原来的 name 修改 nickname

从登陆界面上：
1. 把 phone 修改为 username/phone

从数据库设计上：
1.取消手机号的唯一约束
4.新增 username 字段 启用唯一
5.修改 name 为 nickNam,用作昵称。或者保持 name，备注为nickName

数据迁移方面：
1.把原来的 phone 数据库直接复制到 usename

变更后的业务流程：
新用户注册：
1. 输入 唯一的 username 用于后续登陆
2. 输入 nickname 用于名称展示
3. 输入密码和确认密码
4. 注册成功

新用户登陆：
1. 输入 username 和密码
2. 登录成功

老用户登陆：
1. 输入手机号和密码
2. 登录成功

展望：
1. 增加绑定功能
2. 手机号绑定
3. 邮箱绑定
4. Github 绑定
5. Google 绑定

老用户填写手机不作为  “手机号绑定” 已绑定状态，等后续手机号验证码功能出来，验证后再确认绑定状态！

**Comment by cuixiaorui** [comment]
cool

手机号的功能逻辑可以封装到一个组件内  先保留  后面开验证码之后在放开

其他的都没问题 开干！

**Comment by baboon-king** [comment]
> 5.修改 name 为 nickname,用作昵称。或者保持 name，备注为nickname

这里怎么选择

@cuixiaorui

**Comment by cuixiaorui** [comment]
那就用 nickname 好了

**Comment by cuixiaorui** [comment]
顺便把错误返回信息也优化一下
现在  login 和 signup 失败后给用户的信息都是 “register error!”
不够明确

<img width="707" alt="image" src="https://github.com/cuixueshe/earthworm/assets/12064746/41bb97c3-d11b-4a6b-831a-c17e80f7b4a5">
<img width="635" alt="image" src="https://github.com/cuixueshe/earthworm/assets/12064746/25d3c020-319d-4ecb-adaf-9f6ee8c28a17">
可以让接口直接返回信息  
前端是支持直接显示的
<img width="1054" alt="image" src="https://github.com/cuixueshe/earthworm/assets/12064746/850d4614-c36d-49e2-b1b2-ae8229494ab1">

**Comment by baboon-king** [comment]
I see!

**Comment by baboon-king** [comment]
> @baboon-king
> 
> 看看是否可以基于 https://github.com/sidebase/nuxt-auth 来做
> 
> 正好把 github 登录之类的也都处理掉 #295

ok 没问题。我会在登录功能 phone 迁移到 username 后，然后去做 Github 接入。

**Comment by cuixiaorui** [comment]
done
之后用邮箱+密码的形式注册
有钱了之后开手机号+验证码方式（验证码挺贵）
