### ISSUE TITLE
[BUG] - 第12课 517句子有误

### ISSUE THREAD

**Issue by Silent-wqh** [cuixueshe/earthworm#345]
### Describe the bug

![image](https://github.com/cuixueshe/earthworm/assets/24985177/982c98cc-7e39-4cc9-a9b2-a2d0fcafb1e9)
![image](https://github.com/cuixueshe/earthworm/assets/24985177/fb65c684-1df0-4afe-a3c7-9c8ff6513e96)
中文和英文对不上

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/cuixueshe/earthworm/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/cuixueshe/earthworm/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by fengstats** [comment]
@Silent-wqh 感谢~ 已修复，待下次发版时关闭并通知

**Comment by fengstats** [comment]
@ishowman related to https://github.com/cuixueshe/earthworm/commit/85e661b2365e503b7f76c15a8e25ad8721a0eddb

**Comment by fengstats** [comment]
@Silent-wqh 问题已修复并发版
