### ISSUE TITLE
[BUG] - 没有提交答案前，前面一个单词错了，很难修改

### ISSUE THREAD

**Issue by xcsweb** [cuixueshe/earthworm#346]
### Describe the bug

![image](https://github.com/cuixueshe/earthworm/assets/20693737/cf40f09e-ed0f-464d-8136-263b7fea9809)
 没有提交答案前，前面一个单词错了，很难修改，只有回车提交了，然后按空格键盘才能修改那个，建议可以点击键盘左右键跳转对应的单词，点击空格直接清空该单词

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/cuixueshe/earthworm/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/cuixueshe/earthworm/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by fengstats** [comment]
你好，我明白你的意思，但要考虑到比如你当前有很长的一个句子：he has bought a decorated Christmas tree for his family，当你已经输入到 family 时，此时你发现 has 输入错了，按你所说，使用左右键来跳转单词位置是相当繁琐的，你需要自己不断调整定位单词，同理，当你需要回来当前位置继续输入也要很多次

而 Earthworm 对于 input 的输入理念是：“同一时间只做一件事情”

1. 输入的时候就是输入
2. 改错的时候就是改错

我相信当你深入体验使用了之后就会知道，其实这里改错并不会特别难修改，使用 “回车键” 提交后，如果出现错误，对应错误的单词可以使用 “空格键” 来进行自动定位跳转和清除，当你不小心改错第一个错误单词空格跳转到下一个单词时也可以使用 “退格键”（删除） 回到上一个错误单词，所以这一块暂时不做支持，很多打字软件其实也是类似的操作习惯，而 Earthworm 提供了一些更方便用户操作的快捷方式来辅助，希望理解 😊

![1711006382200](https://github.com/cuixueshe/earthworm/assets/48991003/f7f4f479-697f-4d4f-acc9-818006f3e21d)

**Comment by Silent-wqh** [comment]
我一般是发现了单词错误且比较难修改时直接回车提交。因为提交后出现错误也没有什么惩罚机制，而且这样修改比较方便。

**Comment by fengstats** [comment]
> 我一般是发现了单词错误且比较难修改时直接回车提交。因为提交后出现错误也没有什么惩罚机制，而且这样修改比较方便。

哈哈，不错的操作

**Comment by cuixiaorui** [comment]
后续通过教学视频来演示在 earthworm 中如何修改错误的单词
需要让用户知道 earthworm 对于输入的理念
