### ISSUE TITLE
[BUG] - 不知道算不算句子bug

### ISSUE THREAD

**Issue by xcsweb** [cuixueshe/earthworm#351]
### Describe the bug

![image](https://github.com/cuixueshe/earthworm/assets/20693737/0000eef4-37db-43c7-a113-d4a04ca7ac97)
![image](https://github.com/cuixueshe/earthworm/assets/20693737/5593f1e6-2003-4eb4-9e68-d76744f3d89a)
我用文心一言问的

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/cuixueshe/earthworm/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/cuixueshe/earthworm/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by fengstats** [comment]
可以从顶部工具栏左侧小电视点到对应星荣的课程视频中，看看视频中对应的句子是怎样的，我们这块还是要尽量和星荣视频课程对齐，毕竟是零基础课程

![1711028392656](https://github.com/cuixueshe/earthworm/assets/48991003/5ef01e5d-8a74-423f-8a72-972034dc8cf7)

**Comment by fyzhu** [comment]
want sb to do sth
