### ISSUE TITLE
[BUG] - 不同设备登陆同一个账号，学习进度无法同步。

### ISSUE THREAD

**Issue by firstvip** [cuixueshe/earthworm#353]
### Describe the bug

如题
https://earthworm.cuixueshe.com/main/1

### Reproduction

https://earthworm.cuixueshe.com/main/1

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/cuixueshe/earthworm/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/cuixueshe/earthworm/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by cuixiaorui** [comment]
课程会同步 课程内的题目没做同步

**Comment by firstvip** [comment]
明白了，谢谢！
