### ISSUE TITLE
[BUG] -  是不是升级了什么？登录register error!

### ISSUE THREAD

**Issue by shubo83** [cuixueshe/earthworm#355]
### Describe the bug

<img width="456" alt="image" src="https://github.com/cuixueshe/earthworm/assets/3070621/36b1759c-53b2-48c1-82cf-0caef90691b2">
如图

**Comment by shubo83** [comment]
login接口返回{"data":{},"message":"User not exists"}，我的账号数据丢失？

**Comment by fengstats** [comment]
可以尝试重新注册一下，使用之前的手机号即可~

**Comment by shubo83** [comment]
@fengstats 啊 那数据还在吗？

**Comment by shubo83** [comment]
数据丢失，这太尴尬了

**Comment by fengstats** [comment]
> 数据丢失，这太尴尬了

是我们的问题，十分抱歉 🙇‍♂️🙇‍♂️🙇‍♂️

**Comment by Domainsun** [comment]
什么时候 可以登录使用， 现在应该不要去重新注册吧

**Comment by cuixiaorui** [comment]
数据出现了一点波动 
出现该问题后 可以尝试重新注册一下
