### ISSUE TITLE
[Feature Request] - 增加打字音开关

### ISSUE THREAD

**Issue by aha-weikai** [cuixueshe/earthworm#361]
### Clear and concise description of the problem

快速打字的时候，网页发出的打字音和机械键盘声音同时发出，会比较混乱

### Suggested solution

在设置界面，增加打字音的开关，控制打字音的开启

**Comment by fengstats** [comment]
收到建议，这两天就会增加上线，敬请期待~ 😊

**Comment by fengstats** [comment]
此功能已完成，等发版后会通知并 Close issue~

**Comment by fengstats** [comment]
已上线~
