### ISSUE TITLE
[问题] - 按照文档初始化启动项目失败

### ISSUE THREAD

**Issue by Connell-z** [cuixueshe/earthworm#365]
### Description

![截屏2024-03-23 13 28 28](https://github.com/cuixueshe/earthworm/assets/112607513/d3de5885-c6f1-4c12-91a5-abd9a542b717)
按照文档初始化项目的流程，操作到

**Comment by fengstats** [comment]
@Connell-z 你好，可以尝试下先跑 `pnpm schema:build` 命令

**Comment by Connell-z** [comment]
@fengstats 感谢，跟着文档，能够成功初始化数据库启动， 过程中vscode终端没报错，可控制台报错：http.ts:19 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'data')

**Comment by fengstats** [comment]
控制台指的是浏览器控制台吗？启动后端 + 前端服务后，开发页面等待加载一会资源，如果页面正常显示并可以使用就不需要管了

**Comment by iheai47** [comment]
我也是遇见这个问题，你是跑 pnpm schema:build 命令就行了吗？

**Comment by fengstats** [comment]
@iheai47 最新代码中已经将 `pnpm schema:build` 添加到 `pnpm db:init` 命令中了，按照项目文档步骤来说应该不会有这个问题，出现问题将自己对应的问题截图发出来，包括复现步骤等等，问题描述越清晰，解决越快~

**Comment by iheai47** [comment]
@=

> @iheai47 最新代码中已经将 `pnpm schema:build` 添加到 `pnpm db:init` 命令中了，按照项目文档步骤来说应该不会有这个问题，出现问题将自己对应的问题截图发出来，包括复现步骤等等，问题描述越清晰，解决越快~

我已经重新拉取代码解决了 谢谢！

**Comment by fengstats** [comment]
@iheai47 解决就好 😊

**Comment by iheai47** [comment]
> @iheai47 解决就好 😊

我可以问一个比较小白的问题吗 我作为一个学生 之前学过vue2.0 和若依这样的前后端分离的springboot集成框架。
在面对earthworm这个项目我是不是应该去学习v3.0和nuxt的才能熟悉这整个项目

**Comment by iheai47** [comment]
@fengstats 非常谢谢你！！

**Comment by Connell-z** [comment]
@fengstats 我重新拉了一遍项目，按照文档能一路配置下来，中途没有报错；但前端启动的时候有如下报错
<img width="1076" alt="截屏2024-03-27 11 30 30" src="https://github.com/cuixueshe/earthworm/assets/112607513/e6240594-5315-4fd5-ac14-f91457bad835">
<img width="874" alt="截屏2024-03-27 11 30 14" src="https://github.com/cuixueshe/earthworm/assets/112607513/2e471046-dd15-4469-9fe6-a627ed29725a">
<img width="734" alt="截屏2024-03-27 11 30 07" src="https://github.com/cuixueshe/earthworm/assets/112607513/88c4d43f-52f4-4642-8144-f22b7d55724a">

**Comment by oxh666** [comment]
你是不是只启动了前端， 没有启动后端？ 不光要 pnpm dev:client 还有重新开个终端启动 pnpm dev:serve

**Comment by Mutter45** [comment]
环境：
- Windows 11
- Node 21.4.0
- pnpm 8.15.6

执行pnpm db:init时报
![image](https://github.com/cuixueshe/earthworm/assets/93197952/b7fc45e3-cf56-4c51-b613-c4fca596d56d)
有那位小伙伴遇到嘛

**Comment by jersonwei** [comment]
apple m2
node 20.11.0
pnpm 8.3.0
docker 25.0.3

I had finished step 1 ~step 3,and it was working. 
<img width="746" alt="image" src="https://github.com/cuixueshe/earthworm/assets/102666924/d71d6021-36cb-4473-8c4a-719eb35b2686">
But there was a error when i run the step 4 - pnpm db:init.
<img width="697" alt="image" src="https://github.com/cuixueshe/earthworm/assets/102666924/34c4bbf1-145e-4596-a978-7faaabb34404">
How can i solve this error?

**Comment by ibucoin** [comment]
> apple m2 node 20.11.0 pnpm 8.3.0 docker 25.0.3
> 
> I had finished step 1 ~step 3,and it was working. <img alt="image" width="746" src="https://private-user-images.githubusercontent.com/102666924/320038366-d71d6021-36cb-4473-8c4a-719eb35b2686.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1NDE1OTAsIm5iZiI6MTcxMjU0MTI5MCwicGF0aCI6Ii8xMDI2NjY5MjQvMzIwMDM4MzY2LWQ3MWQ2MDIxLTM2Y2ItNDQ3My04YzRhLTcxOWViMzViMjY4Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOFQwMTU0NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZTg4ZTdhM2VmNDNkYzRlZjU5YzAzOWI4ZmU5NzhlZDJkMWEzODg0ODkwMThjOTNmYmQ5OTk1MjY4ODQ0ZjA3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jUOI6Rwe-6tsLmhUagj0YWhCvr-oiErvGb8vLNtNouY"> But there was a error when i run the step 4 - pnpm db:init. <img alt="image" width="697" src="https://private-user-images.githubusercontent.com/102666924/320039328-34c4bbf1-145e-4596-a978-7faaabb34404.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1NDE1OTAsIm5iZiI6MTcxMjU0MTI5MCwicGF0aCI6Ii8xMDI2NjY5MjQvMzIwMDM5MzI4LTM0YzRiYmYxLTE0NWUtNDU5Ni1hOTc4LTdmYWFhYmIzNDQwNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOFQwMTU0NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZmNjZTViMzMxYmY3YTJkMTlmNWU5NzEzZWY0NDJkMzk0MTg4ZTMxZTEwNWQ3ZDQzMjIyNGY3NDg3OWFiZDdlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.irWcSlWI0NihHOV3_mhE9Tcqqj673qxn6pUd7WGzH_M"> How can i solve this error?

Check if the first step, Install Dependencies, has been correctly executed, whether the project contains the node_modules folder, and if it includes the tsup folder.

**Comment by jersonwei** [comment]
> > apple m2 node 20.11.0 pnpm 8.3.0 docker 25.0.3
> > I had finished step 1 ~step 3,and it was working. <img alt="image" width="746" src="https://private-user-images.githubusercontent.com/102666924/320038366-d71d6021-36cb-4473-8c4a-719eb35b2686.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1NDE1OTAsIm5iZiI6MTcxMjU0MTI5MCwicGF0aCI6Ii8xMDI2NjY5MjQvMzIwMDM4MzY2LWQ3MWQ2MDIxLTM2Y2ItNDQ3My04YzRhLTcxOWViMzViMjY4Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOFQwMTU0NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZTg4ZTdhM2VmNDNkYzRlZjU5YzAzOWI4ZmU5NzhlZDJkMWEzODg0ODkwMThjOTNmYmQ5OTk1MjY4ODQ0ZjA3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jUOI6Rwe-6tsLmhUagj0YWhCvr-oiErvGb8vLNtNouY"> But there was a error when i run the step 4 - pnpm db:init. <img alt="image" width="697" src="https://private-user-images.githubusercontent.com/102666924/320039328-34c4bbf1-145e-4596-a978-7faaabb34404.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1NDE1OTAsIm5iZiI6MTcxMjU0MTI5MCwicGF0aCI6Ii8xMDI2NjY5MjQvMzIwMDM5MzI4LTM0YzRiYmYxLTE0NWUtNDU5Ni1hOTc4LTdmYWFhYmIzNDQwNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOFQwMTU0NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZmNjZTViMzMxYmY3YTJkMTlmNWU5NzEzZWY0NDJkMzk0MTg4ZTMxZTEwNWQ3ZDQzMjIyNGY3NDg3OWFiZDdlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.irWcSlWI0NihHOV3_mhE9Tcqqj673qxn6pUd7WGzH_M"> How can i solve this error?
> 
> Check if the first step, Install Dependencies, has been correctly executed, whether the project contains the node_modules folder, and if it includes the tsup folder.
<img width="391" alt="image" src="https://github.com/cuixueshe/earthworm/assets/102666924/9196f755-287b-4376-8166-1b1e20690ed0">
<img width="371" alt="image" src="https://github.com/cuixueshe/earthworm/assets/102666924/13ebb008-644a-43d7-ae5e-e74d7953e8d3">
 I had reinstalled the dependencies,But there was only the tsup@type folder in node_modules.
