### ISSUE TITLE
[BUG] - 当点击 next 按钮时，出现了401情况

### ISSUE THREAD

**Issue by aha-weikai** [cuixueshe/earthworm#369]
## 描述
一课内容，最后一个单词学完，点击next 按钮，弹出了401情况，页面跳转到了登录页，影响操作感受。
## 分析
登录权限的控制放在课程打卡里面，是否合适

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/cuixueshe/earthworm/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/cuixueshe/earthworm/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by cuixiaorui** [comment]
登录检测逻辑重写了 可以在观察下还有没有这个问题
