### ISSUE TITLE
[优化] - 更安全的 ID 列默认值

### ISSUE THREAD

**Issue by baboon-king** [cuixueshe/earthworm#376]
### Description

当前表 ID 列表均采用 “自增 ID” 来设置新数据的 ID 列。这将带来一些数据安全隐患。

> 自增ID在安全性方面存在一些潜在的问题。由于它们是基于递增的整数生成的，因此可能存在信息泄露的风险。攻击者可以根据自增ID的规律猜测到其他记录的ID，并获得关于数据库中的数据量和其他信息的线索。此外，如果自增ID不是足够长或没有足够的随机性，攻击者可能通过遍历或猜测ID来访问未授权的资源

可以迁移到 更安全的 ID 生成算法，就行 drizzle 所提供的例子那样
```typescript
import { varchar, mysqlTable } from "drizzle-orm/mysql-core";
import { createId } from '@paralleldrive/cuid2';
const table = mysqlTable('table', {
  id: varchar('id', { length: 128 }).$defaultFn(() => createId()),
});
```

https://orm.drizzle.team/docs/column-types/mysql#default-value

**Comment by js-0127** [comment]
可以使用雪花算法， 具体做法，生成一个单例，每次调用生成一个新的雪花数当作id,这种长度只需要在64位，并且是id也是自增，相较于128 位的，性能要好
