### ISSUE TITLE
非常喜欢的学英语方式。能否按这样的方法添加学习单词的功能？

### ISSUE THREAD

**Issue by gdrens** [cuixueshe/earthworm#379]
### Clear and concise description of the problem

把单词分类，然后可以选择单词的类别，随机学习该类别的单词。

### Suggested solution

这样一个网站既能学习句子，又能学习单词

**Comment by cuixiaorui** [comment]
之后会有学习单词的方式
不过形式是用要学习的单词造一个句子  
然后刷句子的方式来学
