### ISSUE TITLE
提示用户不存在

### ISSUE THREAD

**Issue by aurura12** [cuixueshe/earthworm#381]
### Describe the bug

在已经注册学习了几节课的前提下，今天突然要求重新登录，利用chrome保存的账号密码无法登录，提示用户不存在

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/cuixueshe/earthworm/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/cuixueshe/earthworm/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by cuixiaorui** [comment]
重新注册吧 正在查这个问题
