### ISSUE TITLE
[Feature Request] - 当输入错词时要修改，可以默认第一个错词保持focus状态

### ISSUE THREAD

**Issue by jinjidecoco** [cuixueshe/earthworm#383]
#### 当前状态：
![WechatIMG558](https://github.com/cuixueshe/earthworm/assets/17644835/498e6368-3468-43ce-97d7-e8b8f7dce2c4)

#### 优化后状态：

![WechatIMG559](https://github.com/cuixueshe/earthworm/assets/17644835/8beabdf7-53a4-4d04-89af-b1fccbb7be1b)

**Comment by cuixiaorui** [comment]
这是因为要保留错误单词 才这么设计的
直接 focus 第一个单词 
如果不删除 也需要按下 cmd + backspace  
如果删除  那么就没法知道错在哪里了
