### ISSUE TITLE
[优化] - 星荣课程数据的中文语义

### ISSUE THREAD

**Issue by wbs99** [cuixueshe/earthworm#387]
### Description

Description 描述
第 51 课第 3 、4 两个句子的中文语义问题，我通过页面中对应的哔哩哔哩视频链接查看了一下中文是和视频一致的，但结合前后句子来说，不知是否将这两个句子的中文语义适当修改一下会更好一些
<img width="480" alt="51-1" src="https://github.com/cuixueshe/earthworm/assets/83934669/2fdffda6-6024-4475-9b4d-3252b58471b0">
<img width="414" alt="51-2" src="https://github.com/cuixueshe/earthworm/assets/83934669/9319ee31-5f49-42c4-8b45-4f9e45599f80">

**Comment by zuowendong** [comment]
数据来自视频，我感觉存在语义问题的地方是有很多，如果你能够全面的筛选并给出更优的选择，那我认为是值得一个不错的pr

**Comment by zuowendong** [comment]
期待你的pr

**Comment by wbs99** [comment]
> 期待你的pr

因为前期没有过多了解这个项目，偶尔看到几次。我看 `xingrong-courses/data/courses` 中的数据好像是由  `xingrong-courses/data/pdf` 中读取出来的。但好像又不是完全对应，目前有 46 个 pdf 文件，有 51 个 json 文件，我看到类似的 [PR](https://github.com/ishowman/earthworm/commit/08fe7cca19192e9f2c8eee54cad9a4e5be21d544)，以及石头修复这个小细节的 [PR](https://github.com/cuixueshe/earthworm/commit/85e661b2365e503b7f76c15a8e25ad8721a0eddb)，如果我像这两个 PR 一样，将目前的所有的课程的 json 数据过一遍，优化一下语义，不知我这样的做法是否正确，如果这个做法是正确的话，我想我可以开始尝试做一下努力了。

**Comment by fengstats** [comment]
@wbs99 这是个很棒的想法！目前的星荣课程数据中，确实存在很多僵硬的语句翻译如同机翻

但如果用户每次更改 1、2 个的错误就提交 pr 上来的话，我们也会很困扰，对于这种 pr 错误 1、2 个与 10、20 个，review 起来花的时间其实差不多的，进一步查看这些 pr 也会分散一些精力和注意力，作为维护者这并不是我们想看到的

当然，如果你愿意来做这件事情统一处理这些数据问题的话，我们非常期待你的贡献~ 相信在这个过程中大家也会给予你帮助，如果有疑问欢迎随时沟通 😊

对了，其实你仔细看看 pdf 文件就会发现，是有 51 个 pdf 的，那为什么你说是 46 呢，因为最后一个 pdf 标题是 46，其实是因为存在一些 **.5** 课程，这些课程在星荣那边属于 “**复习**” 课程，我们为了统一标题，将这些课程根据序号重新排版了，由此变成了 51 课，意味着你现在看到的第 6 课其实是对应的星荣 5.5.pdf，当然你也可以在答题页面中的小电视快速跳转对应的课程~

![1711530328295](https://github.com/cuixueshe/earthworm/assets/48991003/f79f08d0-4e91-470e-a18f-a26d62930559)

如果你没有进群，也可以添加微信备注：称呼 + Earthworm，拉你进群，群里的小伙伴们也很活跃的，可以一起来打卡讨论！😊

- 崔哥：cuixr1314
- 小石：iFeng-2024

**Comment by ningfc** [comment]
第十二课 286
我认为我们不应该知道这个问题的答案
I don't think we should know the answer to the question 
这里我觉得正确的句子应该是
I think we should not know the answer to the question 
或者中文对应的应该是
我不认为我们应该知道这个问题的答案
这样感觉才是一致的
