### ISSUE TITLE
The frontend css  might needs to be adjust for chrome

### ISSUE THREAD

**Issue by yourmoonlight** [cuixueshe/earthworm#408]
### Description

chrome version: 122.0.6261.128
![截屏2024-03-28 17 39 15](https://github.com/cuixueshe/earthworm/assets/6244271/eca328bd-4b82-4180-8b06-a00e582835c6)

**Comment by HolinWang** [comment]
https://github.com/cuixueshe/earthworm/pull/431

**Comment by fengstats** [comment]
已修复，线上版本体验
