### ISSUE TITLE
[BUG] - 账号学习记录丢失

### ISSUE THREAD

**Issue by Vincent-20481** [cuixueshe/earthworm#411]
### Describe the bug

![001](https://github.com/cuixueshe/earthworm/assets/15389354/886790cf-775b-4b00-aa25-beefb5848e03)
账号学习记录丢失，显示异常，我学完第9科，某一天开始记录错误，账号name：vincent

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/cuixueshe/earthworm/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/cuixueshe/earthworm/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by cuixiaorui** [comment]
目前版本是删档版
过几天就会把所有数据清空
