### ISSUE TITLE
学海无涯何处是头，展示阶梯及学习大纲

### ISSUE THREAD

**Issue by xyh2132** [cuixueshe/earthworm#415]
### Clear and concise description of the problem

学海无涯，打了1个小时，还是第一节，不知道有多少节，不知道记忆了多少个单词或句子，也不知道打几千个词才能回头是岸。
所以给个阶梯式的学习预告，让自己知道自己进展到了哪一步。

### Suggested solution

第一节就218个句子，1个小时还没练完，到底有多少节，说出来让我死心

**Comment by Nauxscript** [comment]
![image](https://github.com/cuixueshe/earthworm/assets/13010589/42d5270d-154b-45e6-8ab0-aa128548c83f)

这里可以查看课程列表
