### ISSUE TITLE
ipad 适配

### ISSUE THREAD

**Issue by cuixiaorui** [cuixueshe/earthworm#417]
### Description

样式上的问题
<img width="1282" alt="image" src="https://github.com/cuixueshe/earthworm/assets/12064746/dba774db-9661-41e0-a874-60a23bdd3516">

图片里是 ipad7

**Comment by Lck6de1p** [comment]
在mac小屏上长句也会有这种问题
![Snipaste_2024-03-28_12-14-35](https://github.com/cuixueshe/earthworm/assets/46702192/3e79bbad-83ac-4c4f-a751-d7bb9e0506fe)

**Comment by HolinWang** [comment]
pls check https://github.com/cuixueshe/earthworm/pull/431
<img width="836" alt="Snipaste_2024-03-30_01-44-02" src="https://github.com/cuixueshe/earthworm/assets/99414027/36bb9245-ec41-4215-8552-b39e54cd96aa">
<img width="768" alt="Snipaste_2024-03-30_01-41-51" src="https://github.com/cuixueshe/earthworm/assets/99414027/bd537796-b1e8-47ee-870e-71ae6416cac1">
<img width="779" alt="Snipaste_2024-03-30_01-38-45" src="https://github.com/cuixueshe/earthworm/assets/99414027/aaa3638c-4492-4cb4-92ca-cc62282d1077">

**Comment by fengstats** [comment]
已修复
