### ISSUE TITLE
实现答案检测的模糊匹配

### ISSUE THREAD

**Issue by cuixiaorui** [cuixueshe/earthworm#418]
### Description

在检测句子正确的时候做模糊匹配

比如  ’  也可以作为 ' 

## why

有些用户是直接打“don’t” 会显示是错误的

这里的 ’ 不是 '  , 这里可以做一个模糊匹配  让用户更舒服一些

有点类似于 wolai 里面你写中文的符号 他自动给你转成对应的英文符号

**Comment by cuixiaorui** [comment]
一开始可以先实现  ’  -> '

后面等用户反馈在一点点扩展

**Comment by Lck6de1p** [comment]
#420 已完成
