### ISSUE TITLE
[BUG] - 第35课的第34个句子存在错误

### ISSUE THREAD

**Issue by Silent-wqh** [cuixueshe/earthworm#419]
### Describe the bug

句子末尾应为`British English`，缺少`English`，并且音标多出了一个`/English/`

![2024-03-29 01-09-18](https://github.com/cuixueshe/earthworm/assets/24985177/11e25eb1-720f-4cea-8238-a4e7edfbea90)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/cuixueshe/earthworm/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/cuixueshe/earthworm/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by TOBYhhw** [comment]
我的设备上没有这个问题

**Comment by fengstats** [comment]
这部分错误已经修改了哈，不过目前还没发版，等下次发版会通知并关闭此 issue 😊

related to https://github.com/cuixueshe/earthworm/pull/348

**Comment by fengstats** [comment]
@Silent-wqh 已经发版啦！
