### ISSUE TITLE
如何增加自己的课程包？

### ISSUE THREAD

**Issue by kkpapa** [cuixueshe/earthworm#429]
### Clear and concise description of the problem

通过代码本地部署，如何增加自己的课程包，有一个简单的Tutorial吗？谢谢

### Suggested solution

有自己的课程目录，目录下面有不同的课程文件

**Comment by cuixiaorui** [comment]
现在还不支持

**Comment by kkpapa** [comment]
有大概的时间点吗

**Comment by cuixiaorui** [comment]
后续关于课程包问题都将会在 #300  讨论
