### ISSUE TITLE
给目录一个背景板

### ISSUE THREAD

**Issue by cuixiaorui** [cuixueshe/earthworm#437]
### Description

<img width="399" alt="image" src="https://github.com/cuixueshe/earthworm/assets/12064746/6dd8c721-bbf0-4061-83ff-014cc2c4d6d1">

现在是透明的
透明的问题在于会和单词混在一起
所以需要一个背景板
注意 目录的显示层级需要在单词之上

**Comment by fengstats** [comment]
注意：要用 TailwindCSS，注意浅色和深色主题显示的适配，默认写的是浅色，深色可以用 `dark:xxx` 来设置，如：`dark:bg-gray-500`
