### ISSUE TITLE
答错三次自动弹出答案 tip 页面

### ISSUE THREAD

**Issue by cuixiaorui** [cuixueshe/earthworm#439]
### Description

<img width="1266" alt="image" src="https://github.com/cuixueshe/earthworm/assets/12064746/88b40257-7516-4793-bcd5-89074ba368ee">

答错三次自动弹出答案 tip 页面
这里是指用户调用“提交答案的动作” 三次
在第三次的时候 就弹出来

## why
解决两个场景

1. 新用户第一次尝试 earthworm 总是输入错误 

很多新用户在第一次尝试 earthworm 的时候遇到 “不”  会输入 no  not 等等进行尝试
结果会发现依然不对 就会直接得出结论 “不好用”

所以我们通过自动弹出答案这个功能来尽可能的解决这个问题

2. 一般输入两次还错  基本就是不会 可以直接看答案了

直接显示答案 也可以让用户更方便一些

**Comment by Hazel-Lin** [comment]
可能存在用户看了答案还是输错的情况，可以一直显示答案 ，直到用户输入正确进入下一题才关闭展示，这样是否可行

**Comment by cuixiaorui** [comment]
done
