### ISSUE TITLE
修复游戏页面内重置进度的问题

### ISSUE THREAD

**Issue by fengstats** [cuixueshe/earthworm#444]
### Description

1. 实现点击 **重置进度** 后自动聚焦输入框（目前需要手动聚焦）
2. 实现当前处于第一个题目并且输入了一些内容后，点击重置进度清除输入的内容

![image](https://github.com/cuixueshe/earthworm/assets/48991003/f1dfccb9-619f-4663-b5fb-a8bf9eaae7ba)

**Comment by cuixiaorui** [comment]
done
