### ISSUE TITLE
修复答案预览页面的显示问题

### ISSUE THREAD

**Issue by fengstats** [cuixueshe/earthworm#445]
### Description

通过快捷键或者点击 “**显示答案**” 后，会在工具栏下方出现一个答案预览模态框，如

<img width="450" alt="image" src="https://github.com/cuixueshe/earthworm/assets/48991003/3fc37e55-51be-49f5-8a3f-f839ccaf6ffc">

执行下面几个动作时应当将其隐藏

1. 切换题目（上/下题目）
2. 重置进度
3. 退出至课程列表，再随意进入一个课程

目前会一直处于显示状态，直到用户执行快捷键触发 “隐藏答案” 或者 “刷新网页” 时才会隐藏

**Comment by fengstats** [comment]
再补充一个问题，目前需要将鼠标悬浮到模态框上才会显示 close 按钮，可以将其变成固定的，因为可能有人（大部分）不知道悬浮之后才会显示，对鼠标用户友好一点~

![image](https://github.com/cuixueshe/earthworm/assets/48991003/66ebf5b3-c04a-4601-ad6f-31631a904a13)

**Comment by cuixiaorui** [comment]
done
