### ISSUE TITLE
改变 Answer 页面的高度

### ISSUE THREAD

**Issue by cuixiaorui** [cuixueshe/earthworm#453]
## what

answer 页面的高度需要和 question 页面的高度对齐

## why

现在答完题跳转到 answer 后 会感觉向上跳

<img width="1223" alt="image" src="https://github.com/cuixueshe/earthworm/assets/12064746/e3066f3a-8ddd-4a27-bd89-5407efba2653">

<img width="1229" alt="image" src="https://github.com/cuixueshe/earthworm/assets/12064746/6125820e-c8ea-436b-95a9-f8d34daddc62">

**Comment by fengstats** [comment]
答题页面和答案页面暂时调整为居中方案，而且现在答案页面元素比答题页面元素更多，所以改变高度的方式不能解决闪一下的问题，后续看看是否可以通过加一个过渡动画的方式来让这种割裂感减少或者消失 😊

![1711907028899](https://github.com/cuixueshe/earthworm/assets/48991003/78f16359-4b9f-4c9b-b469-86f113c1b829)

**Comment by jinjidecoco** [comment]
音标是否可以和语音放在一行

**Comment by fengstats** [comment]
> 音标是否可以和语音放在一行

你要为了长句子考虑，不能只考虑单词，句子很长时放在一行会相当别扭
