### ISSUE TITLE
ipad 提示横屏

### ISSUE THREAD

**Issue by cuixiaorui** [cuixueshe/earthworm#459]
### Description

# what

检测是 ipad 环境并且是竖屏时  提示需要让用户横屏

## why

很多用户是使用 ipad 来玩  earthworm 的 
但是在
竖屏下使用体验不好 （样式适配）
所以提示让用户横屏使用

**Comment by fengstats** [comment]
这个 issue 的内容在 https://github.com/cuixueshe/earthworm/issues/506 中已经包含
