### ISSUE TITLE
我做了一个PTE的wfd的课程包

### ISSUE THREAD

**Issue by zcl0621** [cuixueshe/earthworm#461]
### Description

我做了一个wfd的课程包，目前正在做拆解练习。
请问可以直接添加到贵站的主站内么？
https://github.com/zcl0621/earthworm-wfd

**Comment by DrfterX** [comment]
支持，太需要更多的课程了，现在成内容少而且难度低，不适合成人学英语

**Comment by zcl0621** [comment]
@DrfterX 不知道现在主站支持不支持多课程
准备把RS的加进来

**Comment by DrfterX** [comment]
> @DrfterX 不知道现在主站支持不支持多课程 准备把RS的加进来

大佬好，作为一个只会学英语不会部署的小白，怎么把你的这个分项目部署到自己的vps里呢？我只会照着how to start一行行粘代码部署，但是好像不太细，进行一半报错就不知道怎么进行下去了

**Comment by zcl0621** [comment]
就按照readme啊

先装docker

然后clone repo

pnpm install

cp .env.example ./apps/api/.env

pnpm docker:start

执行完了 等一分钟 有些机器启动数据库要等

pnpm db:init

pnpm db:upload

开个tmux 
pnpm dev:serve

再开个tmux
pnpm dev:client


现在WFD拆解还没做完，我估计一天会拆20个题目。到时候更新repo。执行 pnpm db:update

**Comment by Torstentjh** [comment]
@DrfterX  你在微信群里吗，在的话，公告好像有一些怎么操作的方法，还可以找一个叫小小石的帮你😂

**Comment by cuixiaorui** [comment]
添加多课程的功能还需要等一等
现在还不支持 
不过也快了 
到时候会写帮助文档哈

**Comment by cuixiaorui** [comment]
后续关于课程包问题都将会在 #300  讨论
