### ISSUE TITLE
[BUG] - v1.3.5版本更新后，显示答案后再次按下空格不会清空并跳转到第一条输入位置，很破坏肌肉记忆并且不方便

### ISSUE THREAD

**Issue by WindChime-Echo** [cuixueshe/earthworm#462]
### Describe the bug

v1.3.5版本更新后，显示答案后再次按下空格不会清空并跳转到第一条输入位置，很破坏肌肉记忆并且不方便

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/cuixueshe/earthworm/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/cuixueshe/earthworm/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by fengstats** [comment]
@WindChime-Echo 不是很懂你的意思，目前显示答案更改成了一个预览横幅，这也是为了解决用户反馈的在长句子的题目上，输入了很多内容，某个单词忘记了，通过快捷键显示答案后回来答题，所有输入都被清除了的问题：

- #315 
- #386 

而且目前的答案预览横幅不会影响用户输入，你看完之后隐藏继续输入就好了~ 😊

**Comment by WindChime-Echo** [comment]
@fengstats 抱歉，前几天比较忙，我之前使用tab转换到对应按钮产生的问题，现在也已经习惯了，谢谢
