### ISSUE TITLE
希望把白天夜间模式也放到个人设置里

### ISSUE THREAD

**Issue by LeeeChenn** [cuixueshe/earthworm#465]
### Description

个人比较喜欢夜间模式，不想每次访问都要点击切换夜间模式

**Comment by fengstats** [comment]
@LeeeChenn 现在主题模式数据是存储在浏览器的 Session storage 中的，确实会有关闭后又需要重新切换主题的问题，这块可以将其改到 Local storage 中，欢迎 pr 😊
