### ISSUE TITLE
[功能] - 用户成就系统

### ISSUE THREAD

**Issue by hildxd** [cuixueshe/earthworm#473]
### Description

UI - https://js.design/f/jXz4DN?p=BLC0Ss5GLo&mode=design
数据库设计参考 - https://dbdiagram.io/d/earthworm-achievements-6600e35fae072629ced7f577

记得补充测试，可以找群里小石哥协助

**Comment by hildxd** [comment]
还需要一个发放成就的页面

字段如下：
- 口令
- 用户手机号 (需要查询出用户名展示）
- 发放按钮

**Comment by hildxd** [comment]
发放成就暂时使用手动方式，后续优化成自动

**Comment by baboon-king** [comment]
想知道最新进度？他在这 https://github.com/cuixueshe/earthworm/issues/731
