### ISSUE TITLE
第十二课内容过多，需要拆分

### ISSUE THREAD

**Issue by LeeeChenn** [cuixueshe/earthworm#481]
### Description

第十二课有 566 道题，内容过多，不合理，需要做拆分。

**Comment by wangjunjia** [comment]
我感觉是汇总了前面的课程，类似集中复习一样。我花了三次才完成哈。

**Comment by fengstats** [comment]
@LeeeChenn 你好~ 感谢建议，不过这毕竟是来源于星荣的课程数据，这部分我们还是要做一下对齐的，详情参见：https://github.com/cuixueshe/earthworm/issues/91#issuecomment-2022294397
