### ISSUE TITLE
音效设置

### ISSUE THREAD

**Issue by TheStarsBlink** [cuixueshe/earthworm#488]
### Clear and concise description of the problem

发音需要快捷键，键盘音效没发关闭

### Suggested solution

发音需要快捷键，键盘音效没发关闭

### Describe alternatives you've considered

统一设置是否可以播放发音和键盘快捷键

### Screenshots or Videos

![Uploading 1712160429699.png…]()

### Additional context

https://kaiyiwing.gitee.io/qwerty-learner 参考一下这个

**Comment by fengstats** [comment]
@TheStarsBlink 你好，你发的图片不能正常加载显示（可能是没有上传完毕就开 issue 了）

关于你说的发音快捷键和键盘音效的问题，**先确保你登录了**，点击右上角用户 icon 选择 “**User Info**”，来到设置页面设置选择开启和关闭

<img width="277" alt="image" src="https://github.com/cuixueshe/earthworm/assets/48991003/fd8bcdd7-9425-4f4c-a535-305896f48c12">

![1712160902333](https://github.com/cuixueshe/earthworm/assets/48991003/65c54ca6-2591-4673-86a6-73527c637ed2)

**Comment by TheStarsBlink** [comment]
@fengstats 好的，我很久没退出页面了，所以不知道在设置里面可以改。我在使用我发的参考链接的网站的时候发现，在打字页面更改这些设置很方便，如果可以的话希望可以在打字页面直接修改

**Comment by fengstats** [comment]
> @fengstats 好的，我很久没退出页面了，所以不知道在设置里面可以改。我在使用我发的参考链接的网站的时候发现，在打字页面更改这些设置很方便，如果可以的话希望可以在打字页面直接修改

好的，我们会考虑的，感谢你的提出的宝贵建议~ 😊
