### ISSUE TITLE
[BUG] - 只答了某一课的最后一题也默认通关了

### ISSUE THREAD

**Issue by cyan0714** [cuixueshe/earthworm#495]
### Describe the bug

每一课直接选最后一题答完后默认就通关这一课了，无论前面的题有没有答，用这个方法可以直接冲到榜一

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/cuixueshe/earthworm/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/cuixueshe/earthworm/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by fengstats** [comment]
@cyan0714 你好，这个问题我们内部是知道的，先回答：**后续排行榜不会再使用课程的完成数量进行排名**（重构），关于目录跳转和上一个下一个题目切换，主要是为了缓解多设备同步问题存在的，如 #353 

最后，我相信大部分人参与 earthworm 是奔着学习英语和提升，目前刷排行榜榜一也没有任何奖励，所以应该不会有这么无聊的人，你说是吧 😊

**Comment by cyan0714** [comment]
是的, 这样就失去练习英语的目的了, 我也只是随口提一下, 这是个可以优化的点

**Comment by fengstats** [comment]
> 是的, 这样就失去练习英语的目的了, 我也只是随口提一下, 这是个可以优化的点

好的，收到建议，后续会优化调整~
