### ISSUE TITLE
账号密码输入input框希望加个密码显示

### ISSUE THREAD

**Issue by phy-lei** [cuixueshe/earthworm#496]
### Description

![image](https://github.com/cuixueshe/earthworm/assets/58167763/faebd3b0-7ce2-40e7-ad68-a3f1c6a4233e)
有时候，用了google的密码存储功能，自己忘记原来密码是啥，想直接快速查看自己输入的密码

**Comment by yaolifeng0629** [comment]
@phy-lei 功能已支持 #510 ，待合并可查看

**Comment by cuixiaorui** [comment]
done

**Comment by phy-lei** [comment]
> @phy-lei 功能已支持 #510 ，待 @cuixiaorui 合并可查看

我也加了一个同样功能的pr，不过我发现你这里好像会输入input框过长会这样  
![image](https://github.com/cuixueshe/earthworm/assets/58167763/376729f5-5103-4ba1-a042-16fd9eea04b8)

可以对比看看#513
