### ISSUE TITLE
[BUG] - 使用快捷键可以快速刷完所有课程

### ISSUE THREAD

**Issue by f5l5y5** [cuixueshe/earthworm#499]
### Describe the bug

考虑优化下，感觉这个要整体看一下
![earthworm-ezgif com-video-to-gif-converter](https://github.com/cuixueshe/earthworm/assets/27725420/d026f2a4-15b6-4e97-a98d-d1284958b102)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/cuixueshe/earthworm/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/cuixueshe/earthworm/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by pkc918** [comment]
Please describe in detail

**Comment by pkc918** [comment]
Could you please provide details on how you triggered this issues?

**Comment by fengstats** [comment]
详情说明参见：https://github.com/cuixueshe/earthworm/issues/495#issuecomment-2036560936
