### ISSUE TITLE
[BUG] - 中文输入法下输入单词没法通过回车进入下一题

### ISSUE THREAD

**Issue by TheStarsBlink** [cuixueshe/earthworm#504]
### Describe the bug

![1712318378330](https://github.com/cuixueshe/earthworm/assets/132535285/69ee9d35-725b-4c78-a44b-0d7a9e13ead4)
中文输入法会直接吧整个单词提交。我没看代码，不知道是不是通过检测键盘 key 来显示输入单词的，我猜测是中文输入法输入打字时候没有出触发导致的

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/cuixueshe/earthworm/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/cuixueshe/earthworm/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by wangjunjia** [comment]
中文状态下的回车输入法会选中文字并上屏，还是尽量使用英文输入模式，毕竟是输入英文嘛。

**Comment by cuixiaorui** [comment]
done
