### ISSUE TITLE
[BUG] - Mac 切换下一题快捷键失效

### ISSUE THREAD

**Issue by Kevinmaomao** [cuixueshe/earthworm#507]
### Describe the bug

window.addEventListener("keydown", handler)监听不到ctrl+.事件，但是可以监听到ctrl+shift+.组合键，是否需要变更成ctrl+shift+.组合键跳转下一题

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/cuixueshe/earthworm/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/cuixueshe/earthworm/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by wangjunjia** [comment]
我试了一下，是可以监听到的，你看看是不是输入法不是英文模式或者其他原因。

**Comment by pkc918** [comment]
输入法不管中英文，我这都可以下一和上一

**Comment by fengstats** [comment]
@Kevinmaomao 你好，我并不能复现这个问题，是否可以提供更详细的复现步骤或者其他的补充说明？感谢~

**Comment by yanghuanrong** [comment]
这个问题在我的电脑也是一样，我尝试修复这个问题。经过研究以及询问 AI 得到下面的回答。
> 在 Mac 操作系统中，Ctrl + . 组合键通常与快速输入省略号（…）的功能相关联。然而，与其他操作系统或键盘布局不同，Mac 默认使用 Option 键（在 Windows 键盘上通常对应 Alt 键）来访问特殊字符，而不是 Ctrl 键。
为了在使用 Mac 时触发 Ctrl + . 组合键，你可能需要同时按下 Shift 键，这是因为 Mac 键盘的 Ctrl 键在没有 Shift 配合的情况下通常不用于输入特殊字符。
