### ISSUE TITLE
[疑问]inputValue不是已经使用v-model双向绑定了吗？这里赋值操作的意图是什么呢？

### ISSUE THREAD

**Issue by refanbanzhang** [cuixueshe/earthworm#522]
https://github.com/cuixueshe/earthworm/blob/c391edc7e2366901a98f9a2818cad9a5015c932b/apps/client/components/main/QuestionInput/QuestionInput.vue#L20

https://github.com/cuixueshe/earthworm/blob/c391edc7e2366901a98f9a2818cad9a5015c932b/apps/client/composables/main/question.ts#L50

```
function setInputValue(val: string) {
  inputValue.value = val; // 这一行的意图是？
  resetAllWordUserInput();
  inputSyncUserInputWords();
  updateActiveWord(val ? getInputCursorPosition() : 0);
}
```

**Comment by wangjunjia** [comment]
这是一种设计思路，当前刚好是一个 input ，没有多个联动，所以显得多余。但是如果需要和别的联动的话，比如被动跟随或者自定义 input model 时，这个 useInput 就可以自己内部管理输入值了。

**Comment by refanbanzhang** [comment]
> 这是一种设计思路，当前刚好是一个 input ，没有多个联动，所以显得多余。但是如果需要和别的联动的话，比如被动跟随或者自定义 input model 时，这个 useInput 就可以自己内部管理输入值了。

感谢，虽然现在脑子里没能具体关联到你说的场景，后面有空我会仔细思考一下。
