### ISSUE TITLE
[BUG] - 听写模式下答案提示框位置偏移

### ISSUE THREAD

**Issue by zuowendong** [cuixueshe/earthworm#525]
### 如图

![image](https://github.com/cuixueshe/earthworm/assets/45628596/830c844a-acf1-4416-a6e2-b29e9ef7564c)

### 期待

和 `中译英` 模式下一致，保持弹窗居中显示

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/cuixueshe/earthworm/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/cuixueshe/earthworm/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by wangjunjia** [comment]
这个我来处理吧，我定位到问题了

**Comment by zuowendong** [comment]
> 这个我来处理吧，我定位到问题了

正确的pr流程参见 #91
