### ISSUE TITLE
[BUG] - 回车提交之后再按空格，没有聚焦到第一个错误单词

### ISSUE THREAD

**Issue by seemrcola** [cuixueshe/earthworm#543]
### Describe the bug

bug复现方案图如下：

<img width="850" alt="bug" src="https://github.com/cuixueshe/earthworm/assets/110106669/4ab368f0-ea84-4b4b-ae44-dc8bb0dcae93">

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/cuixueshe/earthworm/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/cuixueshe/earthworm/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by cuixiaorui** [comment]
done
