### ISSUE TITLE
[功能] - 丰富结算页面数据记录

### ISSUE THREAD

**Issue by zuowendong** [cuixueshe/earthworm#553]
### Description

丰富结算页面，也可以作为分享页的一种类型

完善通关数据，更贴合游戏概念

类似这种效果

![image](https://github.com/cuixueshe/earthworm/assets/45628596/b36fde3e-3cd7-447f-bbd3-3a513b737978)

目前只有完成题目数的耗时

新增，例如

- 当前课程刷的次数
- 平均耗时，最快/慢的耗时
- 此次通关的时间，如果是重复刷的话，也可以展示曾经一天中最早的通关时间 / 最晚时间
- 主动查看答案的次数
- 跳过的题目个数
- 连击次数
- ...

Inspired by @Nauxscript 

大伙儿还有什么更好的想法？

**Comment by ANTHAK** [comment]
可以记录单个 语句的录入时间，根据句子长度按照一定规则生成不同的录入区间。
