### ISSUE TITLE
[BUG] - 突然不能登录了

### ISSUE THREAD

**Issue by thunder-gzy** [cuixueshe/earthworm#555]
### Suddenly I can’t log in

Can't log in
<img width="1382" alt="WechatIMG17866" src="https://github.com/cuixueshe/earthworm/assets/58799014/92104e47-47c9-4fcb-a5ca-1ad275c82eac">

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/cuixueshe/earthworm/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/cuixueshe/earthworm/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by fengstats** [comment]
@thunder-gzy Hello, can you check if the password is wrong?

**Comment by thunder-gzy** [comment]
@fengstats Oh, the password is really wrong!
