### ISSUE TITLE
[优化] - tailwindss => unocss

### ISSUE THREAD

**Issue by phy-lei** [cuixueshe/earthworm#566]
### Description

对于nuxt而言，感觉unocss与其更加贴切，并且项目上有很多图标都是直接写svg标签的，这对于可读性来说略差，unocss有比较好的集成icon，这在tailwindcss中icon的集成丰富程度并没有unocss高。

若考虑迁移的话，难点：
- 兼容tailwindcss样式
- theme的暗夜白天模式
- daisyui插件兼容

迁移后优点：
- icon统一管理，项目上不再充斥svg，可读性变高
- 官方标配

**Comment by fengstats** [comment]
@phy-lei 感谢建议~ 目前正在做这部分调整，现在项目中的 icon 全是使用 svg 标签的方式引入，确实会影响开发时的代码阅读体验

不过迁移方案，暂时不考虑 UnoCSS 了，还是 [Iconify for Tailwind CSS](https://iconify.design/docs/usage/css/tailwind/)

也不用将所有 icon 管理都集成进来，需要什么 icon 自行安装对应的 icon sets 包即可，可以先找两个比较全面的包
