### ISSUE TITLE
[功能] - 键盘打字音效定制

### ISSUE THREAD

**Issue by itchaox** [cuixueshe/earthworm#571]
### Clear and concise description of the problem

在开启键盘音效后，增加几个其他的音效（打字机、冒泡、剑气）等

### Suggested solution

在开启键盘音效后，增加几个单选项来切换不同的音效

**Comment by CAN1177** [comment]
关于音效，可参考这个项目： https://github.com/yingDev/Tickeys
可以增加 架子鼓的音效， 练习时可以来一段“爆裂鼓手”， 音效文件来源： 
[16053__logicogonist__dw-drum-kit 2.zip](https://github.com/cuixueshe/earthworm/files/14965121/16053__logicogonist__dw-drum-kit.2.zip)

**Comment by CAN1177** [comment]
突然又想到，既然可以切换不同音效，那就新增一些‘彩虹屁’： https://github.com/SaekiRaku/vscode-rainbow-fart

**Comment by itchaox** [comment]
> 关于音效，可参考这个项目： https://github.com/yingDev/Tickeys 可以增加 架子鼓的音效， 练习时可以来一段“爆裂鼓手”， 音效文件来源： [16053__logicogonist__dw-drum-kit 2.zip](https://github.com/cuixueshe/earthworm/files/14965121/16053__logicogonist__dw-drum-kit.2.zip)

我就是看的这个软件，才想起提的这个 Issue，哈哈哈🤣
