### ISSUE TITLE
[功能] - 输入区域可以改为一条线

### ISSUE THREAD

**Issue by coderlfm** [cuixueshe/earthworm#574]
## 背景
我的需求来源是，因为现在单词的输入区域，是有一个个分段的下划线的__ __，这个下划线它可以给我起到一些辅助作用，它会提示我这个句子一共由几个单词组成。

如下面这个示例，我大概可以猜到有后面是什么单词，尽管这个示例比较简单，但应该足以展示我需要表达的意思。

<img width="618" alt="image" src="https://github.com/cuixueshe/earthworm/assets/59016499/87ffc8d7-c5a3-4a3d-b399-e562c881c167">

当我想要检验自己是否完全掌握这些内容的时候，以及当我对某个课程二刷的时候，下划线的辅助会让我错误的让我感觉我掌握了这些内容。
<br/>

## 期望
是否可以在单词的输入位置是一长条下划线，它随着我输入的内容长度而增长，它不会起任何提示作用，如此才可以检验我是否真正的掌握了这些单词，而不是自我麻醉，大致效果如下所示。
<img width="324" alt="image" src="https://github.com/cuixueshe/earthworm/assets/59016499/75179bf9-b460-4f79-8c41-bca54ee4d61d">

所以是否可以在设置或者其它位置增加个功能开关，开启这个开关后，单词的输入区域就变成一整条线，有人和我一样有这个需求吗。

**Comment by himkiong** [comment]
建议在输入页放这个开关或者快捷键
场景: 如果突然遇到一句不太会的，但是又不想听语音，想要单词数量的提示，这样会方便一些

**Comment by coderlfm** [comment]
各位同学，我有几个功能具体实现时的小细节，和各位讨论一下。

## 用户是否可以输入任意长度的内容？
举例：假设答案是 `I like to do it now`，一共是6个单词。
那么用户是否输入到6个单词后就限制其输入？
如：
`I like to do it now`
`I evry like to do it now`
`I like to do it now AAA AAA AAA AAA AAA`

如果只允许用户输入6个字符，那么当用户发现它无法继续输入的时候，会察觉到它好像输入错了，从而开始检查自己填写的单词是否有问题，这会导致检查提前，从而无法检验自己是否完完全全零错误的写对了该句子。

所以我的想法是，可以让用户输入超出标准答案长度的内容。
那如果以此为前提的话，可能会产生出下述两个问题。
<br/>

## 用户可以输入的超出答案多少长度？
`I like to do it now`这个句子的长度是19，那么该限制用户输入长度多少合适？
如果不限制长度肯定不行，极端情况下可能会超出整个屏幕，从而导致UI错乱。
超出多少字符，这个值该定多少？允许用户超出50个字符或100个？
<br/>

## 句子出错时的提示策略
举例：假设答案是 `I like to do it now`，但是用户可能输入的内容可能会比答案的句子更长，或者更短。那么当用户输入的内容出错时，该如何给用户进行错误提示呢？


### 策略1：只提示错误的内容
以下测试案例中，加粗和有背景色的位置为错误的提醒区域。

输入：I AAA to do it now，两种提示方式，选哪种？
 - 提示：I **`AAA`** to do it now
<br/>


输入：I like AAA BBB CCC to do it now，两种提示方式，选哪种？
 - 提示：I like **`AAA BBB CCC`** to do it now
 - 提示：I like **`AAA BBB CCC to do it now`**
<br/>

用户少填了单词的情况
输入：I to do it now
- 提示：I **`to do it now`**

输入：I now
- 提示：I **`now`**

输入：I
- 提示：？？？

输入： (空格)
- 提示：？？？
<br/>



### 策略2：统一提示，不做精准错误提示
这种方式可以避免在策略1中，如果用户少输入了单词时，该如何错误提示的问题。
只要用户输入的句子任意单词错了，导致和标准答案不匹配，那么便整个句子都是错误的。
<br/>

### 想法
基于以上原因，我目前的想法是：
允许用户输入任意长度，但会加上超出标准答案长度的限制，以防止输入的内容过于离谱。
出错时，以整句话都报错的方式进行错误提示。

各位同学有其它可行性的想法欢迎讨论。

**Comment by seemrcola** [comment]
统一报错/不给详细提示的方案很适合听写模式。

**Comment by cuixiaorui** [comment]
“允许用户输入任意长度，但会加上超出标准答案长度的限制，以防止输入的内容过于离谱。
出错时，以整句话都报错的方式进行错误提示。”

可行 [强]

**Comment by xiaodong2008** [comment]
I will take on this.
