### ISSUE TITLE
按下 ctrl+p 后 光标的位置跑到了第一个

### ISSUE THREAD

**Issue by cuixiaorui** [cuixueshe/earthworm#58]
光标应该还在原来的位置

现在一输入跑第一个位置去了

**Comment by hildxd** [comment]
@zclsx

**Comment by fengstats** [comment]
Ctrl+p 快捷键的功能是在输入框内移动至内容的最前面，对应的 Ctrl+n 功能为移动到最后面，由于未阻止默认事件而导致出现此问题。
