### ISSUE TITLE
[BUG] - 首页【开启EarthWorm】按钮样式错乱

### ISSUE THREAD

**Issue by yaolifeng0629** [cuixueshe/earthworm#584]
### 样式错乱
	如下图：
<img width="800" alt="c478d174f03388b0ed309868ed84e85" src="https://github.com/cuixueshe/earthworm/assets/88535417/1383286e-5de7-42f5-a9c0-00efbc855a34">

### 重现过程：
	1. 根据之前用户反馈，是在 ipad 的 Safari 浏览器 打开会异常，所以重现如下。
	2. 在ipad pro 2021 上 Safari 浏览器正常打开 earthworm 首页，样式正常。
		如下图：
	
![2172384a9a54a0ded13bf01017767c4](https://github.com/cuixueshe/earthworm/assets/88535417/db134747-5014-4112-b836-bb756154befd)

### 结论：
	1. 目前暂定可能与浏览器的版本有关，不兼容按钮的某些样式。（待确定）

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/cuixueshe/earthworm/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/cuixueshe/earthworm/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by yaolifeng0629** [comment]
那位小伙伴遇到了同样问题，麻烦这里留言下，提供信息模板如下：

> 机型：Mac / Window
> 浏览器：Google / Safari / IE / Firefox / Edge / Opera
> console 控制台输出台截图

**Comment by orangelckc** [comment]
提供一个稳定复现的环境
"userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko)"

**Comment by fengstats** [comment]
目前通过在 `开启 Earthworm` 按钮上添加 `relative` 定位的方式解决，之前能复现问题的小伙伴们可以拉取最新的代码再看看，或者等更新正式版在官网看 😊

**Comment by cuixiaorui** [comment]
目前没有人在反馈此问题
