### ISSUE TITLE
[BUG] -第 29 课的第 26 题 `you can` 发音不对

### ISSUE THREAD

**Issue by CAN1177** [cuixueshe/earthworm#586]
### Describe the bug

* 问题录屏：
https://github.com/cuixueshe/earthworm/assets/39960526/c6160e59-36dd-4827-bfc1-e31b71c7998e
 * 正确读音可在这里测试：
https://tophonetics.com/zh/

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/cuixueshe/earthworm/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/cuixueshe/earthworm/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by fengstats** [comment]
@CAN1177 你好，在后续版本更新时会修复掉~ 非常感谢反馈！😊

顺便解释下这个问题，目前项目中使用的是 **有道 Web 翻译 API 接口** 手动测试部分单词和句子后，发现这两个接口是可以直接使用的，参数设置如下：

```javascript
 // 美式发音：https://dict.youdao.com/dictvoice?type=0&audio=word
 // 英式发音：https://dict.youdao.com/dictvoice?type=1&audio=word
```

但是刚刚拿了 `you can` 去测试发现美式发音很奇怪 → [you can - 美式（异常）](https://dict.youdao.com/dictvoice?type=0&audio=you%20can)

于是乎想着调整了下 `type` 参数，改成了 2 到 5（从 6 开始就是和 0 一样的了），发现也是美式的发音，而且这次是正确的 → [you can - 美式](https://dict.youdao.com/dictvoice?type=2&audio=you%20can)

反复测试了部分单词和句子，发现都没问题，所以发音后续参数设置会更改为：

```javascript
 // 英式发音：https://dict.youdao.com/dictvoice?type=1&audio=word
 // 美式发音：https://dict.youdao.com/dictvoice?type=2&audio=word
```
