### ISSUE TITLE
浏览器安装 FeHelper(前端助手) 插件后，页面会展示 json 数据

### ISSUE THREAD

**Issue by HenryTSZ** [cuixueshe/earthworm#59]
<img width="1332" alt="image" src="https://github.com/cuixueshe/earthworm/assets/55341525/536bc44b-bb6b-467c-9efc-ab5c1554a1a7">

**Comment by Nauxscript** [comment]
是不是和插件的特性有关 没有用过这个插件

**Comment by myltx** [comment]
这个应该是插件问题，我在插件的 issue 中找到了类似的问题 目前作者好像还没有给出具体的答复 [JSON美化的BUG](https://github.com/zxlie/FeHelper/issues/311)

**Comment by hildxd** [comment]
@seyeeL

**Comment by whenTheMorningDark** [comment]
我的也是 哈哈

**Comment by hildxd** [comment]
#66
