### ISSUE TITLE
[BUG] - 使用邮箱注册的用户没有用户名和昵称

### ISSUE THREAD

**Issue by baboon-king** [cuixueshe/earthworm#591]
### Describe the bug

使用邮箱注册的用户没有用户名 (username)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/cuixueshe/earthworm/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/cuixueshe/earthworm/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by cuixiaorui** [comment]
follow up on this issue ： https://github.com/logto-io/logto/issues/5707

**Comment by cuixiaorui** [comment]
统一下方案：

用户邮箱登录 -> callback 弹出让他改 name  -> 检测 name 需要是唯一的（logto 会检测） ->  我们手动设置 username 和 name 一样 

1. 可以在 settings 页面修改 name 
2. 右上角显示 name
3. 排行榜返回 username

**Comment by cuixiaorui** [comment]
<img width="915" alt="image" src="https://github.com/cuixueshe/earthworm/assets/12064746/ac3967d5-765e-4154-862d-63aa31e1b90b">

logto api 会检测 username 是否唯一

**Comment by cuixiaorui** [comment]
done
