### ISSUE TITLE
12课 185 翻译不是很通顺

### ISSUE THREAD

**Issue by WindChime-Echo** [cuixueshe/earthworm#594]
### Description

中文：他需要知道是否我可以明天在这里 
英文：He needs to know if I can be here tomorrow
翻译成：他需要知道我明天是否可以在这里 更符合中文语序吧

**Comment by fengstats** [comment]
你好 #421 中已经有修改这部分内容，欢迎帮我们 review 添加评论，感谢~ 🙏
