### ISSUE TITLE
[功能] - 在账户设置页增加修改昵称的功能

### ISSUE THREAD

**Issue by baboon-king** [cuixueshe/earthworm#604]
### Clear and concise description of the problem

在账户信息-> 设置 提供个人信息设置，以提供昵称修改功能

### Suggested solution

作为用户，我希望
1. 点击右上角 `Account Info`
2. 点击设置
3. 聚焦到个人信息设置
4. 有一个输入框显示了我的昵称
5. 点击输入框
6. 输入新的昵称
7. 点击更新或者按下回车键
8. 成功修改昵称

**Comment by BambooSword** [comment]
我来
