### ISSUE TITLE
[BUG] - 完成第四课后，给第一课增加了一次完课记录

### ISSUE THREAD

**Issue by itheword** [cuixueshe/earthworm#625]
### Describe the bug

好像第四题结束后自动加记录到第一题了,虽然我不太确定
![image](https://github.com/cuixueshe/earthworm/assets/113843834/0032c23e-93b8-4191-bb31-98f1455259a9)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/cuixueshe/earthworm/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/cuixueshe/earthworm/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by baboon-king** [comment]
> 自动加记录
这个加记录是什么意思，能详细一点吗

**Comment by cuixiaorui** [comment]
现在你在试一试
