### ISSUE TITLE
[BUG] - 首页底部 icon 不显示

### ISSUE THREAD

**Issue by yaolifeng0629** [cuixueshe/earthworm#628]
### Describe the bug

之前：
![image](https://github.com/cuixueshe/earthworm/assets/88535417/213a482a-1e6a-4ab2-b66f-1947b2bfc791)

现在：
![1713455033856](https://github.com/cuixueshe/earthworm/assets/88535417/4d940039-48ba-4fab-abdf-73f0d21cfd8d)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/cuixueshe/earthworm/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/cuixueshe/earthworm/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by baboon-king** [comment]
有复现地址吗

**Comment by fengstats** [comment]
@yaolifeng0629 拉取最新代码，显示效果如下：

![1713585167928](https://github.com/cuixueshe/earthworm/assets/48991003/d4c96fcb-a3b9-45be-83ad-42bb6aa224b8)

![1713585113195](https://github.com/cuixueshe/earthworm/assets/48991003/538ea661-636d-4053-9bce-8dd7af3317a5)
