### ISSUE TITLE
光标位置错误

### ISSUE THREAD

**Issue by inscorpio** [cuixueshe/earthworm#63]
输入单词过程中，使用方向键会移动光标
由于使用 `opacity-0` 隐藏了 input 输入框，不容易发现光标位置改变的问题，但是会导致后续删除字母错误
是否需要考虑输入单词的过程中禁用方向键或显示光标位置

**Comment by hildxd** [comment]
🤔确实有这个问题，虽然我不会按到方向键，算一个优化点把。显示光标就要舍去一部分美观，取舍。先待定把

**Comment by cuixiaorui** [comment]
这个问题非常有必要解决

不小心碰到方向键就和摸瞎一样了

难点在于如何优雅美观的提示用户当前的光标所在的问题

大家可以发表下自己的想法和建议

<img width="274" alt="image" src="https://github.com/cuixueshe/earthworm/assets/12064746/fca656f7-3ac5-44ec-bc41-2115e3059d0b">

下方出现一个小箭头 代替光标如何？（有点丑 哈哈

**Comment by cuixiaorui** [comment]
done 现在的方案是禁止用户左右移动
