### ISSUE TITLE
【待分类】具体情景见录屏

### ISSUE THREAD

**Issue by orangelckc** [cuixueshe/earthworm#630]
### Description

改代码的时候忽然发现目前线上的版本在完成一个小节之后切换，会直接看到对应小节的答案，不知道是不是BUG

https://github.com/cuixueshe/earthworm/assets/48410934/4a50c57d-5f11-4ee3-9375-7da887574325

**Comment by fengstats** [comment]
@orangelckc 本地最新版本已修复此问题，等待后续发布正式版本 😊

**Comment by orangelckc** [comment]
PLEASE IGNORE
不好意思，没在最新的代码测试，这个问题已经解决了
