### ISSUE TITLE
[BUG] - 第50课的第13个句子存在错误

### ISSUE THREAD

**Issue by Silent-wqh** [cuixueshe/earthworm#634]
### Describe the bug

出现了额外的音标

![2024-04-21 12-32-56](https://github.com/cuixueshe/earthworm/assets/24985177/7c593093-f8bc-46e9-a7f7-1b56eb7e9937)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/cuixueshe/earthworm/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/cuixueshe/earthworm/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by yaolifeng0629** [comment]
@Silent-wqh 感谢你的指正，已修复 见 #635

**Comment by cuixiaorui** [comment]
done
