### ISSUE TITLE
[BUG] -听写模式语音延迟

### ISSUE THREAD

**Issue by iwangdonghui** [cuixueshe/earthworm#637]
### Describe the bug

1. 第三课和第四课播放间隔为1秒，偶尔会有好几秒的延迟，有时候甚至不会朗读。
2. Chrome Version 124.0.6367.61 (Official Build) (x86_64)

### Reproduction

1. 第三课和第四课播放间隔为1秒，偶尔会有好几秒的延迟，有时候甚至不会朗读。 2. Chrome Version 124.0.6367.61 (Official Build) (x86_64)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/cuixueshe/earthworm/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/cuixueshe/earthworm/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by fengstats** [comment]
@iwangdonghui 你好，有具体的复现步骤，或者更详细的描述提供吗？方便我们更快的定位问题，感谢~ 😊

**Comment by cuixiaorui** [comment]
可能是网络问题
之后服务器会迁移到国内在加上 cdn 就会好了
