### ISSUE TITLE
[BUG] - 第一课133

### ISSUE THREAD

**Issue by vcvvvc** [cuixueshe/earthworm#646]
### Describe the bug

![image](https://github.com/cuixueshe/earthworm/assets/39010651/8498fa13-a95a-47fb-8fa6-bb2372311353)

发音是我听错了吗，我听着是It is important to do 'do' it

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/cuixueshe/earthworm/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/cuixueshe/earthworm/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by yaolifeng0629** [comment]
@vcvvvc 感谢你的指正，验证了下，发音是正确的。
