### ISSUE TITLE
[BUG] - 现在不能登陆（i can not to login）

### ISSUE THREAD

**Issue by beixiyo** [cuixueshe/earthworm#654]
### Describe the bug

我注册完后，点击登陆页面没有跳转。地址栏一大串东西是不是弄错了

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/cuixueshe/earthworm/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/cuixueshe/earthworm/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by nariii0** [comment]
我也是
