### ISSUE TITLE
[BUG] -第 47 课 ‘to do it’ 发音不对

### ISSUE THREAD

**Issue by CAN1177** [cuixueshe/earthworm#655]
### Describe the bug

录屏在这里：
https://github.com/cuixueshe/earthworm/assets/39960526/a59de412-cea6-43d2-82d1-d52a87b008ef

是否和之前这个issue 有关： #586 ?

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/cuixueshe/earthworm/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/cuixueshe/earthworm/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by cuixiaorui** [comment]
修好了 done
