### ISSUE TITLE
[问题] - 低版本webview，课程包封面在亮色主题下，背景颜色未同步

### ISSUE THREAD

**Issue by orangelckc** [cuixueshe/earthworm#661]
### Describe the bug

低版本webview，课程包封面在亮色主题下，背景颜色未同步
![image](https://github.com/cuixueshe/earthworm/assets/48410934/285265f1-93a0-46cc-a82b-95aa3ae64e0b)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/cuixueshe/earthworm/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/cuixueshe/earthworm/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by orangelckc** [comment]
补充一下，modal这里也会有同样的问题，主题不会同步
![image](https://github.com/cuixueshe/earthworm/assets/48410934/18b12298-17dd-4422-824b-9d56d066d041)
![image](https://github.com/cuixueshe/earthworm/assets/48410934/ce51a0fa-7aa9-4ef5-ba63-b35cbb6d09cd)
![image](https://github.com/cuixueshe/earthworm/assets/48410934/b8bcd908-1aa3-40cb-a151-2f2fa525d94e)
![image](https://github.com/cuixueshe/earthworm/assets/48410934/de393748-6444-4ed1-8771-f3ecbf2a79cc)

**Comment by orangelckc** [comment]
找到问题了，是系统主题的冲突导致的，解决方案还没找到

https://github.com/cuixueshe/earthworm/assets/48410934/ca1e5235-e730-4c05-9669-cf544b4789d3

**Comment by baboon-king** [comment]
看起来是我们暗黑模式的适配问题
