### ISSUE TITLE
[问题] - 用户下拉菜单层级渲染问题

### ISSUE THREAD

**Issue by orangelckc** [cuixueshe/earthworm#670]
### Describe the bug

![image](https://github.com/cuixueshe/earthworm/assets/48410934/deded1de-d34d-444c-b5e0-5f67db41e244)

点击用户头像的DropMenu层级过低，会被其他图标覆盖

【复现环境】——线上正式版
【预期效果】——下拉菜单在其他图标的上面

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/cuixueshe/earthworm/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/cuixueshe/earthworm/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Hazel-Lin** [comment]
应该是 icon 的层级和页面层级影响到了，只调整 tooltip 的层级就好

**Comment by yaolifeng0629** [comment]
@orangelckc 已修复，详情 #689
