### ISSUE TITLE
[优化] - 课程列表页抽离出放在弹窗

### ISSUE THREAD

**Issue by zuowendong** [cuixueshe/earthworm#671]
### Description

减少一层页面路由跳转

**Comment by cuixiaorui** [comment]
一般查看课程列表也只有第一次选择课程的时候
会从“课程包页面” -> "课程列表页"
后续用户大多数的情况是直接从最近的课程包列表直接进入课程，或者是课程列表了

第二是很多情况下是需要展示课程列表的
比如首页的最近课程包点击课程
game 页面返回课程列表
用弹窗的话 效果也没那么好
