### ISSUE TITLE
[BUG] - 本地未登录状态，可直接进入课程列表页面

### ISSUE THREAD

**Issue by yaolifeng0629** [cuixueshe/earthworm#672]
### Describe the bug

- 本地是未登录状态，登录/注册 安装都是  404 状态，但 开始按钮可直接跳转到课程列表页面
-	详情见如下视频：
https://github.com/cuixueshe/earthworm/assets/88535417/603ee2d7-e687-4b66-9780-4d33044121d8

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/cuixueshe/earthworm/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/cuixueshe/earthworm/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by baboon-king** [comment]
@yaolifeng0629 没有复现成功。
尝试无痕访问，再次点击登录，确认 404问题 是否还存在
