### ISSUE TITLE
[BUG] - 多课程包页面切换课程，路由改变，内容未变

### ISSUE THREAD

**Issue by S-H-Go** [cuixueshe/earthworm#677]
### Describe the bug

点击进入`星荣零基础学英语`，内容正确
![image](https://github.com/cuixueshe/earthworm/assets/73683678/b1875f0c-b043-40ad-9de0-a0ac20d6087a)
返回，点击进入`英语零基础写作课程`，路由正确，内容错误
![image](https://github.com/cuixueshe/earthworm/assets/73683678/0f87d3d1-714e-4279-af99-4e9de3a27385)
刷新后内容恢复正确
![image](https://github.com/cuixueshe/earthworm/assets/73683678/98675a6e-5e48-4ee2-ad22-a58e4496afae)
路由更新后没有重新获取数据、更新界面。

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/cuixueshe/earthworm/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/cuixueshe/earthworm/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by cuixiaorui** [comment]
done 下个版本修复
