### ISSUE TITLE
[BUG] - 无法播放英语声音

### ISSUE THREAD

**Issue by WindChime-Echo** [cuixueshe/earthworm#681]
### Describe the bug

![image](https://github.com/cuixueshe/earthworm/assets/67351121/7ece8e34-562b-4a8b-b615-85b003667634)
在调用时调用对象为空

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/cuixueshe/earthworm/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/cuixueshe/earthworm/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by WindChime-Echo** [comment]
在25课发现此问题，抽查第一课，第七课，第二十四课没有此问题

**Comment by WindChime-Echo** [comment]
重新进入25课此问题消失，重复触发bug条件未知

**Comment by fengstats** [comment]
@WindChime-Echo 无法播放指的是播放时没有反应吗？

如果是这样，是否是在该时间段内所有题目点击播放都没反应？还是只有某一个题目点击没有反应，希望能提供更详细的说明方便我们排查问题，感谢 😊

**Comment by WindChime-Echo** [comment]
@fengstats 播放时25课程完全没有反应，只有打字机声音和完成声音，发现play函数调用出错
流程：打开最新课程 =>25课 =>前几个都很简单所以我没有听声音，迅速的过了几条 =>发现没有声音bug

**Comment by cuixiaorui** [comment]
之前服务器在国外 现在迁移到国内了 这个问题应该是可以得到缓解了
