### ISSUE TITLE
网站登录没反应

### ISSUE THREAD

**Issue by weiweiweigang** [cuixueshe/earthworm#684]
### Describe the bug

https://earthworm.cuixueshe.com/ 这个网站点击登录没有反应；并且控制台有报错

### Reproduction

https://earthworm.cuixueshe.com/ 

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/cuixueshe/earthworm/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/cuixueshe/earthworm/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by fengstats** [comment]
@weiweiweigang 你好，能提供更详细的说明方便我们排查问题吗？感谢 😊

**Comment by jcestlavie** [comment]
我也遇到同样的问题

**Comment by jcestlavie** [comment]
Uploading Video_2024-08-04_134725.mp4…
