### ISSUE TITLE
救救孩子，https证书过期，无法摸鱼学习

### ISSUE THREAD

**Issue by linjunjin** [cuixueshe/earthworm#686]
### Description

救救孩子，https证书过期，无法摸鱼学习

**Comment by fengstats** [comment]
@linjunjin 你好，请问一下是使用的公司网络吗（VPN 或者公司路由可能会有屏蔽导致无法访问）？有没有使用手机热点测试过呢？

刚刚查看了下证书是有效的哦，当前时间：2024-05-16 03:57:06

> 如图

![1715802972177](https://github.com/cuixueshe/earthworm/assets/48991003/91b4f62c-95f8-4bd0-96cb-c7c22bbd4149)
