### ISSUE TITLE
[样式] - 首页头像在加载过程时出现多余边框线条

### ISSUE THREAD

**Issue by fengstats** [cuixueshe/earthworm#698]
### Description

看了看应该貌似是浏览器 img 的默认样式，但是不知道具体是哪个样式，尝试直接在 img 上设置 `border-none` 也无效

![image](https://github.com/cuixueshe/earthworm/assets/48991003/d462fb6c-fc93-41a9-84fd-e66050963656)

将 overflow-hidden 放开可以更直观的看到这个问题

![image](https://github.com/cuixueshe/earthworm/assets/48991003/823dd2cb-3efc-447a-a906-04baaa9b231d)

**Comment by aaaaa-pi** [comment]
图片加载失败或还没有加载出来时浏览器会有默认的“图裂”和边框样式
1：替换默认img，可以用一张透明底图来占位
2：如果没有图片的时候不展示img，有图片的时候才展示

**Comment by fengstats** [comment]
> 图片加载失败或还没有加载出来时浏览器会有默认的“图裂”和边框样式 1：替换默认img，可以用一张透明底图来占位 2：如果没有图片的时候不展示img，有图片的时候才展示

感谢建议，这个问题已经修复了，用了个取巧的方式，外层 `div` 固定宽高，`img` 通过给定高度来自适应拉伸图片（`object-fit: cover`），若图片不存在或者加载失败则显示外层的背景色（没有宽度）
