### ISSUE TITLE
可以将 “control + h” 快捷键加进去么？

### ISSUE THREAD

**Issue by shrimpnine** [cuixueshe/earthworm#707]
### Clear and concise description of the problem

删除字符的时候每次都需要换一下手。

### Suggested solution

😊这样小拇指就不用去按退格键了。

可以的话把其他控制光标的快捷键也加入进去。
control + B
control + F
control + P
control + N
control + H
control + D
control + A
control + E

**Comment by zuowendong** [comment]
更简单的做法，建议支持自定义快捷键设置

**Comment by baboon-king** [comment]
> control + B
control + F
control + P
control + N
control + H
control + D
control + A
control + E

分别代表啥功能呢？

**Comment by shrimpnine** [comment]
https://gist.github.com/zhulianhua/befb8f61db8c72b4763d
