### ISSUE TITLE
刚注册，课程相关封面不显示

### ISSUE THREAD

**Issue by Vincent-20481** [cuixueshe/earthworm#708]
### Describe the bug

![78615ad1-c934-4903-b2e2-6d948bad2d5a](https://github.com/cuixueshe/earthworm/assets/15389354/03b46a50-8ec7-4295-ba73-6839237379b7)
课程相关封面不显示

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/cuixueshe/earthworm/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/cuixueshe/earthworm/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by baboon-king** [comment]
你好！现在还能复现吗。
如果你是 Web 开发者，能看看这些图片是 404，还是加载失败了。

如果你能提供你的 大致物理位置，如浙江，网络环境，是否使用代理等信息就更好了。

**Comment by Vincent-20481** [comment]
今天发现可以显示了，这个bug关闭吧
