### ISSUE TITLE
[TXT] - Bathed in sunshine, the runners crossed

### ISSUE THREAD

**Issue by GamenRoll** [cuixueshe/earthworm#713]
### Describe the bug

Bathed in sunshine, the runners crossed _the_ Renmin Park and ran along the artificial lake, sweat soaking their clothes.

### Reproduction
Bathed in sunshine, the runners crossed **Renmin Park** and ran along the artificial lake, **with** sweat soaking their clothes.

不敢微信登录反馈，换个平台吧
TXT选择是个更大的事儿，建议放弃任何来自China的文本。一定要from native **American** English speaker的。
后续看看，我争取有所贡献。

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/cuixueshe/earthworm/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/cuixueshe/earthworm/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by cuixiaorui** [comment]
？ 有啥不敢微信登录反馈的？
