### ISSUE TITLE
[问题] - Logto在docker镜像中报错

### ISSUE THREAD

**Issue by BallerJay** [cuixueshe/earthworm#725]
### Describe the bug

Logto在docker镜像中报错  无法启动，导致无法进入登录页面
<img width="818" alt="image" src="https://github.com/cuixueshe/earthworm/assets/47693122/6115eaa7-15e0-4cc1-a02e-c39299a9af83">

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/cuixueshe/earthworm/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/cuixueshe/earthworm/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by BenWyy** [comment]
我也遇到相同问题想请教下怎么解决的？

**Comment by AdamBear** [comment]
同样问题仍然会出现，怎么解决？

**Comment by hdj258** [comment]
> 同样问题仍然会出现，怎么解决？

我是ubuntu24.04系统
    我出现的第一个问题是logtoPostgres服务也没启动，root账号不存在
    1, docker-compose.yml中的logtoPostgres的user: root 修改成 user: postgres
    第二个问题是logto要修改数据库结构，但是docker-compose.yml的logtoPostgres没映射到宿主机
    2, logtoPostgres添加端口映射
       ports:
        - "5432:5432"
    3, 在宿主机终端运行npm i @logto/cli -g 安装Logto CLI
       在宿主机终端运行logto db alteration deploy更新数据库结构
       postgresql://postgres:p0stgr3s@localhost:5432/logto（这个地址是问ai问出来的，还真可以）
       选择最新数据库
    4,重启docker: docker compose stop && docker compose up -d
