### ISSUE TITLE
[BUG] -53课155 样式bug

### ISSUE THREAD

**Issue by WindChime-Echo** [cuixueshe/earthworm#726]
### Describe the bug

![Snipaste_2024-06-27_09-38-17](https://github.com/cuixueshe/earthworm/assets/67351121/38c442fe-9144-474f-9e85-be860972d387)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/cuixueshe/earthworm/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/cuixueshe/earthworm/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by yaolifeng0629** [comment]
@WindChime-Echo 感谢你的指出，已修正
