### ISSUE TITLE
[BUG] - 53课 63/155 缺少语音

### ISSUE THREAD

**Issue by PublicWorld** [cuixueshe/earthworm#732]
### Describe the bug

![41935b404ac1f6de4dbf52ef5eb5971e](https://github.com/cuixueshe/earthworm/assets/12987627/4a28e4ee-6148-4cdf-850d-4c7f46ff2dce)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/cuixueshe/earthworm/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/cuixueshe/earthworm/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by PublicWorld** [comment]
@cuixiaorui @fengstats  没有人处理这个问题吗？ 
@yaolifeng0629  只会关 issue 吗？

**Comment by yaolifeng0629** [comment]
@PublicWorld 我测试了多台电脑暂时没有复现，麻烦再确认下，我们再看下

**Comment by cuixiaorui** [comment]
https://github.com/user-attachments/assets/1e416a3c-12ff-42a6-8c80-887c5b8b4347

请检查你自己的网络问题   在播放语音的时候 如果网络有问题 就会失败
