### ISSUE TITLE
【功能bug】- 单词步骤条

### ISSUE THREAD

**Issue by Berthua** [cuixueshe/earthworm#734]
### Description

建设某一个课程我学习到第10个单子，返回之后选择其他课程也直接再第十个单词的位置显示

**Comment by Berthua** [comment]
![功能](https://github.com/cuixueshe/earthworm/assets/78671633/08eee368-6e98-4824-b5c5-35ad208669b7)

**Comment by yaolifeng0629** [comment]
@Berthua  这个功能还是要照顾大多数用户习惯，暂不支持。

问题在于，如果其他课程都从第10个单词开始学习，就会导致用户被迫跳过每门课程的前9个单词，无法完整学习课程内容。

**Comment by Berthua** [comment]
您好，可能我的标题表述不太清晰，我不是想要这个功能，这是一个bug，是系统现在的情况，请看gif图

**Comment by cuixiaorui** [comment]
恩 现在的逻辑是一个课程包只会存一个课程的进度
其他的课程的进度就会清空
不存所有的进度主要是服务器的压力
后面会做优化
前端会缓存所有课程的进度
