### ISSUE TITLE
[BUG]  当天早上的记录会算到前一天

### ISSUE THREAD

**Issue by yaolifeng0629** [cuixueshe/earthworm#741]
### Describe the bug

-	描述：
	-	目前测试发现，早上8点前（具体时间点尚不明确）的学习记录被误记为前一天。
-	期望：
	-	学习记录应正确归属当天。

![image](https://github.com/user-attachments/assets/a7e0ecfc-0b9e-4bbe-9b97-b5531ca15cc2)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/cuixueshe/earthworm/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/cuixueshe/earthworm/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by cuixiaorui** [comment]
这块即将被重构掉
以后显示每天的学习时间
因为随着课程包的多元化 这里显示学习次数已经意义不大了
