### ISSUE TITLE
[BUG] - 课程中带有音标字母提交错误

### ISSUE THREAD

**Issue by KingPinone** [cuixueshe/earthworm#745]
### **Description**
日常英语对话100句 
在课程中发现工作与求职 第30  的音标“é” 输入“e”的确认完会提示不正确,无法提交至下一题目。
![image](https://github.com/user-attachments/assets/bfade645-a648-4a16-bba0-dad1e0e7a0cf)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/cuixueshe/earthworm/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/cuixueshe/earthworm/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by cuixiaorui** [comment]
done
