### ISSUE TITLE
给予代码贡献的同学特殊的标识

### ISSUE THREAD

**Issue by cuixiaorui** [cuixueshe/earthworm#76]
## what

贡献过代码的同学 显示特殊的标识

## why

鼓励同学们积极 pr

## 功能设计

- 标识需要分级别， 不同级别显示不同的标识 
   - 可以加一个贡献值的概念，不同贡献值对应不同的标识/图标
   - 第一个版本可以先通过接口添加贡献者以及贡献值（后续在迭代加上 UI 页面）
- 标识应该现在显示哪里？

**Comment by ANTHAK** [comment]
有选择好的图标吗？

**Comment by cuixiaorui** [comment]
该需求合并到 #473
