### ISSUE TITLE
切换课程的时候需要显示 loading

### ISSUE THREAD

**Issue by cuixiaorui** [cuixueshe/earthworm#79]
有几个行为没有显示 loading

比如从结算页面进入的下一关就没有显示 loading

其他的case 需要在发现补充

**Comment by Hazel-Lin** [comment]
2.2

**Comment by fengstats** [comment]
目前这个 Loading 的显示是基于是在 Game 视图中是否有 `currentStatement.id` 来判断的

所以本质上是 courseStore 中的 `currentStatement`（当前题目信息）一直被保留所以才会造成

有两个方案可以处理：

1. 将 courseStore 中的课程信息重置
2. 在 Main/[id].vue 中进行统一拦截操作，默认 isLoading 状态为 true，等待 coursesStore.setup() 获取数据完成后正常显示页面数据将 isLoading 设置为 false
