### ISSUE TITLE
可设置是否开启自动播放声音

### ISSUE THREAD

**Issue by cuixiaorui** [cuixueshe/earthworm#81]
## what

通过设置按钮来控制跳转到 answer 的时候是否自动播放单词的声音

## why

有的同学可能不需要自动播放  比较的烦

## 设计

- 这个控制按钮放在哪里？

**Comment by Nauxscript** [comment]
这个估计放在个人设置中比较合适，但是如果是个人设置，可能就要等 v2 的个人主页；或者可以先做一个简单的设置页，但是也要考虑后续的设置迁移问题。
