### ISSUE TITLE
优化进入 game 的体验

### ISSUE THREAD

**Issue by cuixiaorui** [cuixueshe/earthworm#85]
现在点击 go and get it 按钮后  会等待 start 接口的返回， 返回后才会进入到 game 

用户感觉是卡卡的

<img width="322" alt="image" src="https://github.com/cuixueshe/earthworm/assets/12064746/ed7d2bfd-9193-4067-9b43-4a3dd9c897c5">

<img width="1714" alt="image" src="https://github.com/cuixueshe/earthworm/assets/12064746/fa85794f-c893-499f-baa3-cd5582f850fb">

## 优化方案

改变调用 start 接口的时机
进入主页的时候 就请求 start 接口  返回数据
注意这个接口的调用不应该阻塞主流程 （也就是不可以使用 await ，需要使用 then  返回数据过来后存起来）

还需要处理一个 edge case  如果用户在 start 接口返回数据之前按下了 “go and get it” 按钮 ， 那么需要一个 loading ui 进行展示

### why 

为什么不在点击按钮的时候显示 loading ，让用户等待呢？ 

主要还是为了用户体验

**Comment by fengstats** [comment]
**解决方案**

> 主页

1. 用户进入主页调用 start 接口，把 start 接口返回的课程 cId 存储到浏览器 localStorage 中
2. 点击 "go and get it" 时检查是否存在 cId
	- 存在，直接进入即可
	- 不存在，请求 start 接口并更新 cId，过程中显示 Loading 页面

> 课程页

1. 完成当前课程，在结算面板点击 “开始下一课” 时
2. 利用 fetchCompleteCourse 接口返回的下一课 id 来更新 cId
