### ISSUE TITLE
课程切换后显示问题

### ISSUE THREAD

**Issue by myltx** [cuixueshe/earthworm#87]
问题举例：
1. 当在第一课时完成一个句子后，显示中文答案，这时候退出当前课程进去其他课程，会显示的还是上一课程最后操作题目的答案；
2. 跟上一个操作顺序一样，这时候会显示新进入课程的第一个例句的答案。

https://github.com/cuixueshe/earthworm/assets/29727848/98272873-16b8-42d0-bf2d-57bc0b13bb25

**Comment by cuixiaorui** [comment]
#79 

等这个问题解决完 就好了
到时候应该会先显示 loading  等到数据加载完成后 在显示题目

**Comment by myltx** [comment]
嗯嗯 但是我看代码是在切换课程的时候没有将 gameMode 的值重置 这样进入其他课程的时候 gameMode 还是上一次的 answer  就会导致直接显示了答案出来了

**Comment by fengstats** [comment]
已将默认视图（答题页面）处理放到 [id].vue 中解决
