### ISSUE TITLE
如何参与项目的 PR 贡献？

### ISSUE THREAD

**Issue by fengstats** [cuixueshe/earthworm#91]
主要是涉及到的 **规范** / **流程** / **注意事项**，后续会将这些内容会写到 CONTRIBUTING.md 文档中，大家可以在这里讨论或者补充建议，十分感谢 🙏

**Comment by fengstats** [comment]
不再使用 issues + 留言 deadline 认领的方式占据任务，因为

1. 如果 deadline 太长可能会阻塞该任务进度，让其他有时间并且想 pr 的同学无法参与实现；
2. 针对一个功能/问题，如果有多个 pr 的话也可以方便对比实现

看看和自己实现的有哪里不一样，比一比到底谁的解决思路更好一些，继续 pr

**Comment by fengstats** [comment]
在 pr 前创建一个 issue 用来描述问题或展开讨论，pr 主要是用来解决问题的

一个 pr 可以对应一个或多个 issue，可以在 commit message 或者 pr 的 comment 中提供对应的 issue 关联信息，比如 related to #66 ，closed #88， part of #110 等，方便其他人去查看对应 issue

**Comment by fengstats** [comment]
要注意 commit 格式，参考文档：[约定式提交](https://www.conventionalcommits.org/zh-hans/v1.0.0-beta.4/)

**Comment by fengstats** [comment]
> 不再使用 issues + 留言 deadline 认领的方式占据任务，因为
> 
> 1. 如果 deadline 太长可能会阻塞该任务进度，让一些有时间并想 pr 的同学无法参与进来
> 2. 针对一个功能/问题，有多个 pr 的也可以方便对比实现
> 
> 看看和自己实现的有哪里不一样，比一比到底谁的解决思路更好一些，继续 pr

**举例说明**

A 同学解决了 issue，提交了 pr 然后 merge 了

但是这时候 B 同学其实也解决了这个 issue，代码已经写好了  

那么对于 B 同学来讲，可以先看看 A 同学的解决思路是不是比自己更优秀

如果不如自己，那么嘿嘿嘿继续提交 pr，指出自己的解决方案为什么更优

如果自己的解决方案不如 A 同学， 那么 B 同学正好也学到了更优秀的解决思路~

**Comment by fengstats** [comment]
提交 PR 详细流程可以参考：[如何给想贡献的仓库提交 PR？](https://github.com/fengstats/note/blob/main/posts/GitHub.md#%E5%A6%82%E4%BD%95%E6%8F%90%E4%BA%A4%E4%B8%80%E4%B8%AA-pull-request)

**Comment by refanbanzhang** [comment]
前端想参与，后端服务和数据库能出个简易的安装配置说明吗？

**Comment by fengstats** [comment]
> 前端想参与，后端服务和数据库能出个简易的安装配置说明吗？

@refanbanzhang 你好，关于安装配置等等启动步骤，在项目的说明文档中都有，目前后端服务和数据库都是通过 docker 启动的，根据文档中 **如何开始** 一步步来即可，遇到问题可以随时反馈，链接地址：[如何开始？](https://github.com/cuixueshe/earthworm/blob/main/README.zh-CN.md#-%E5%A6%82%E4%BD%95%E5%BC%80%E5%A7%8B)

**Comment by refanbanzhang** [comment]
> > 前端想参与，后端服务和数据库能出个简易的安装配置说明吗？
> 
> @refanbanzhang 你好，关于安装配置等等启动步骤，在项目的说明文档中都有，目前后端服务和数据库都是通过 docker 启动的，根据文档中 **如何开始** 一步步来即可，遇到问题可以随时反馈，链接地址：[如何开始？](https://github.com/cuixueshe/earthworm/blob/main/README.zh-CN.md#-%E5%A6%82%E4%BD%95%E5%BC%80%E5%A7%8B)

好的，谢谢！

**Comment by fengstats** [comment]
提交 pr 时，尽量统一使用的英文 title 和 commit msg，一个好的 pr 标题应该简洁明了的概述改动的主要内容，而提交信息应该详细的描述改动的原因、范围以及影响，这有助于维护项目的整体一致性和专业性 😊

![image](https://github.com/cuixueshe/earthworm/assets/48991003/2cd04692-7b45-437b-9313-d1cc72127d99)

**Comment by fengstats** [comment]
**关于星荣课程数据的更改说明**

英文太多一词多义，一般更改的其实没什么问题，主要是目前 Earthworm 中的课程内容是需要和星荣的视频课程对齐的，所以没什么必要修改这部分内容，不然后续比如有看视频的用户来刷课程发现对不上，这时候咋办？如果和视频不一致，此时可以附上截图这样（虽然有点难找），方便我们看一眼就能确认好，很快就能合~

除非很离谱的错误，不然我们也需要去看一眼视频课程里面的确认之后才能合，所以有时候也会比较耗时，感谢理解~

- [星荣零基础学英语](https://www.bilibili.com/video/BV13g411F7Kd/)

如果是一些机翻僵硬的问题，可以到这个 issue 中进行留言帮助，一人力量虽小，但团队的力量是强大的，非常感谢您！

- https://github.com/cuixueshe/earthworm/issues/387
- https://github.com/cuixueshe/earthworm/issues/387#issuecomment-2022273717
