### ISSUE TITLE
部分中文语句不通顺

### ISSUE THREAD

**Issue by Turing-jiang** [cuixueshe/earthworm#97]
5.5课的中文语句不通顺。
“I want to know if it is possible to do it today”目前对应中文是“我想要知道今天做这件事是否”，
应改为“我想知道今天是否有可能做这件事”。

已经提交了PR。
在这个issue下面，可以留言其他课中还有哪些中文语句不通顺，可以统一进行修复。

**Comment by cuixiaorui** [comment]
已经修复
关于语句问题还是对应多个 issue 吧

不然不知道是否已经修复
